/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  ConnectionHealthResponse,
  CreateConnectionRequest,
  CreateConnectionResponse,
  GetConnectionResponse,
  ListConnectionsResponse,
  TableProfileResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ConnectionHealthResponseFromJSON,
    ConnectionHealthResponseToJSON,
    CreateConnectionRequestFromJSON,
    CreateConnectionRequestToJSON,
    CreateConnectionResponseFromJSON,
    CreateConnectionResponseToJSON,
    GetConnectionResponseFromJSON,
    GetConnectionResponseToJSON,
    ListConnectionsResponseFromJSON,
    ListConnectionsResponseToJSON,
    TableProfileResponseFromJSON,
    TableProfileResponseToJSON,
} from '../models/index';

export interface CheckConnectionHealthRequest {
    connectionId: string;
}

export interface CreateConnectionOperationRequest {
    createConnectionRequest: CreateConnectionRequest;
}

export interface DeleteConnectionRequest {
    connectionId: string;
}

export interface GetConnectionRequest {
    connectionId: string;
}

export interface GetTableProfileRequest {
    connectionId: string;
    schema: string;
    table: string;
}

export interface PurgeConnectionCacheRequest {
    connectionId: string;
}

export interface PurgeTableCacheRequest {
    connectionId: string;
    schema: string;
    table: string;
}

/**
 * 
 */
export class ConnectionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for checkConnectionHealth without sending the request
     */
    async checkConnectionHealthRequestOpts(requestParameters: CheckConnectionHealthRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling checkConnectionHealth().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/health`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Test connectivity to the remote database. Returns health status and latency.
     * Check connection health
     */
    async checkConnectionHealthRaw(requestParameters: CheckConnectionHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectionHealthResponse>> {
        const requestOptions = await this.checkConnectionHealthRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectionHealthResponseFromJSON(jsonValue));
    }

    /**
     * Test connectivity to the remote database. Returns health status and latency.
     * Check connection health
     */
    async checkConnectionHealth(requestParameters: CheckConnectionHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectionHealthResponse> {
        const response = await this.checkConnectionHealthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createConnection without sending the request
     */
    async createConnectionRequestOpts(requestParameters: CreateConnectionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createConnectionRequest'] == null) {
            throw new runtime.RequiredError(
                'createConnectionRequest',
                'Required parameter "createConnectionRequest" was null or undefined when calling createConnection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateConnectionRequestToJSON(requestParameters['createConnectionRequest']),
        };
    }

    /**
     * Register a new database connection. Provide the source type and connection config (host, port, database, etc.). Credentials can be supplied inline (password/token fields are auto-converted to secrets) or by referencing an existing secret by name or ID. Schema discovery runs automatically after registration.
     * Create connection
     */
    async createConnectionRaw(requestParameters: CreateConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateConnectionResponse>> {
        const requestOptions = await this.createConnectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateConnectionResponseFromJSON(jsonValue));
    }

    /**
     * Register a new database connection. Provide the source type and connection config (host, port, database, etc.). Credentials can be supplied inline (password/token fields are auto-converted to secrets) or by referencing an existing secret by name or ID. Schema discovery runs automatically after registration.
     * Create connection
     */
    async createConnection(requestParameters: CreateConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateConnectionResponse> {
        const response = await this.createConnectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteConnection without sending the request
     */
    async deleteConnectionRequestOpts(requestParameters: DeleteConnectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling deleteConnection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a connection and its cached data.
     * Delete connection
     */
    async deleteConnectionRaw(requestParameters: DeleteConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteConnectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a connection and its cached data.
     * Delete connection
     */
    async deleteConnection(requestParameters: DeleteConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConnectionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getConnection without sending the request
     */
    async getConnectionRequestOpts(requestParameters: GetConnectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling getConnection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get details for a specific connection, including table and sync counts.
     * Get connection
     */
    async getConnectionRaw(requestParameters: GetConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetConnectionResponse>> {
        const requestOptions = await this.getConnectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetConnectionResponseFromJSON(jsonValue));
    }

    /**
     * Get details for a specific connection, including table and sync counts.
     * Get connection
     */
    async getConnection(requestParameters: GetConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetConnectionResponse> {
        const response = await this.getConnectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTableProfile without sending the request
     */
    async getTableProfileRequestOpts(requestParameters: GetTableProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling getTableProfile().'
            );
        }

        if (requestParameters['schema'] == null) {
            throw new runtime.RequiredError(
                'schema',
                'Required parameter "schema" was null or undefined when calling getTableProfile().'
            );
        }

        if (requestParameters['table'] == null) {
            throw new runtime.RequiredError(
                'table',
                'Required parameter "table" was null or undefined when calling getTableProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/tables/{schema}/{table}/profile`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace(`{${"schema"}}`, encodeURIComponent(String(requestParameters['schema'])));
        urlPath = urlPath.replace(`{${"table"}}`, encodeURIComponent(String(requestParameters['table'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get column-level statistics for a synced table. Returns per-column profiles including cardinality, null counts, and type-specific details (distinct values for categorical columns, min/max for temporal/numeric, length stats for text). Profiles are computed at sync time.
     * Get table profile
     */
    async getTableProfileRaw(requestParameters: GetTableProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TableProfileResponse>> {
        const requestOptions = await this.getTableProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TableProfileResponseFromJSON(jsonValue));
    }

    /**
     * Get column-level statistics for a synced table. Returns per-column profiles including cardinality, null counts, and type-specific details (distinct values for categorical columns, min/max for temporal/numeric, length stats for text). Profiles are computed at sync time.
     * Get table profile
     */
    async getTableProfile(requestParameters: GetTableProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TableProfileResponse> {
        const response = await this.getTableProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConnections without sending the request
     */
    async listConnectionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all registered database connections.
     * List connections
     */
    async listConnectionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListConnectionsResponse>> {
        const requestOptions = await this.listConnectionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListConnectionsResponseFromJSON(jsonValue));
    }

    /**
     * List all registered database connections.
     * List connections
     */
    async listConnections(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListConnectionsResponse> {
        const response = await this.listConnectionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for purgeConnectionCache without sending the request
     */
    async purgeConnectionCacheRequestOpts(requestParameters: PurgeConnectionCacheRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling purgeConnectionCache().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/cache`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Purge all cached data for a connection. The next query against these tables will trigger a fresh sync from the remote source.
     * Purge connection cache
     */
    async purgeConnectionCacheRaw(requestParameters: PurgeConnectionCacheRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.purgeConnectionCacheRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Purge all cached data for a connection. The next query against these tables will trigger a fresh sync from the remote source.
     * Purge connection cache
     */
    async purgeConnectionCache(requestParameters: PurgeConnectionCacheRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.purgeConnectionCacheRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for purgeTableCache without sending the request
     */
    async purgeTableCacheRequestOpts(requestParameters: PurgeTableCacheRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling purgeTableCache().'
            );
        }

        if (requestParameters['schema'] == null) {
            throw new runtime.RequiredError(
                'schema',
                'Required parameter "schema" was null or undefined when calling purgeTableCache().'
            );
        }

        if (requestParameters['table'] == null) {
            throw new runtime.RequiredError(
                'table',
                'Required parameter "table" was null or undefined when calling purgeTableCache().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connections/{connection_id}/tables/{schema}/{table}/cache`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));
        urlPath = urlPath.replace(`{${"schema"}}`, encodeURIComponent(String(requestParameters['schema'])));
        urlPath = urlPath.replace(`{${"table"}}`, encodeURIComponent(String(requestParameters['table'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Purge the cached data for a single table. The next query will trigger a fresh sync.
     * Purge table cache
     */
    async purgeTableCacheRaw(requestParameters: PurgeTableCacheRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.purgeTableCacheRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Purge the cached data for a single table. The next query will trigger a fresh sync.
     * Purge table cache
     */
    async purgeTableCache(requestParameters: PurgeTableCacheRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.purgeTableCacheRaw(requestParameters, initOverrides);
    }

}
