/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  ConnectionTypeDetail,
  ListConnectionTypesResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ConnectionTypeDetailFromJSON,
    ConnectionTypeDetailToJSON,
    ListConnectionTypesResponseFromJSON,
    ListConnectionTypesResponseToJSON,
} from '../models/index';

export interface GetConnectionTypeRequest {
    name: string;
}

/**
 * 
 */
export class ConnectionTypesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getConnectionType without sending the request
     */
    async getConnectionTypeRequestOpts(requestParameters: GetConnectionTypeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getConnectionType().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connection-types/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get configuration schema and authentication requirements for a specific connection type.
     * Get connection type details
     */
    async getConnectionTypeRaw(requestParameters: GetConnectionTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectionTypeDetail>> {
        const requestOptions = await this.getConnectionTypeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectionTypeDetailFromJSON(jsonValue));
    }

    /**
     * Get configuration schema and authentication requirements for a specific connection type.
     * Get connection type details
     */
    async getConnectionType(requestParameters: GetConnectionTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectionTypeDetail> {
        const response = await this.getConnectionTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConnectionTypes without sending the request
     */
    async listConnectionTypesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connection-types`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all available connection types, including native sources and FlightDLT services.
     * List connection types
     */
    async listConnectionTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListConnectionTypesResponse>> {
        const requestOptions = await this.listConnectionTypesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListConnectionTypesResponseFromJSON(jsonValue));
    }

    /**
     * List all available connection types, including native sources and FlightDLT services.
     * List connection types
     */
    async listConnectionTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListConnectionTypesResponse> {
        const response = await this.listConnectionTypesRaw(initOverrides);
        return await response.value();
    }

}
