/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CreateEmbeddingProviderRequest,
  CreateEmbeddingProviderResponse,
  EmbeddingProviderResponse,
  ListEmbeddingProvidersResponse,
  UpdateEmbeddingProviderRequest,
  UpdateEmbeddingProviderResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CreateEmbeddingProviderRequestFromJSON,
    CreateEmbeddingProviderRequestToJSON,
    CreateEmbeddingProviderResponseFromJSON,
    CreateEmbeddingProviderResponseToJSON,
    EmbeddingProviderResponseFromJSON,
    EmbeddingProviderResponseToJSON,
    ListEmbeddingProvidersResponseFromJSON,
    ListEmbeddingProvidersResponseToJSON,
    UpdateEmbeddingProviderRequestFromJSON,
    UpdateEmbeddingProviderRequestToJSON,
    UpdateEmbeddingProviderResponseFromJSON,
    UpdateEmbeddingProviderResponseToJSON,
} from '../models/index';

export interface CreateEmbeddingProviderOperationRequest {
    createEmbeddingProviderRequest: CreateEmbeddingProviderRequest;
}

export interface DeleteEmbeddingProviderRequest {
    id: string;
}

export interface GetEmbeddingProviderRequest {
    id: string;
}

export interface UpdateEmbeddingProviderOperationRequest {
    id: string;
    updateEmbeddingProviderRequest: UpdateEmbeddingProviderRequest;
}

/**
 * 
 */
export class EmbeddingProvidersApi extends runtime.BaseAPI {

    /**
     * Creates request options for createEmbeddingProvider without sending the request
     */
    async createEmbeddingProviderRequestOpts(requestParameters: CreateEmbeddingProviderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createEmbeddingProviderRequest'] == null) {
            throw new runtime.RequiredError(
                'createEmbeddingProviderRequest',
                'Required parameter "createEmbeddingProviderRequest" was null or undefined when calling createEmbeddingProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/embedding-providers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEmbeddingProviderRequestToJSON(requestParameters['createEmbeddingProviderRequest']),
        };
    }

    /**
     * Register a new embedding provider that can be used to generate vector embeddings for text columns. Providers can be service-based (e.g., OpenAI) or local.
     * Create embedding provider
     */
    async createEmbeddingProviderRaw(requestParameters: CreateEmbeddingProviderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEmbeddingProviderResponse>> {
        const requestOptions = await this.createEmbeddingProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateEmbeddingProviderResponseFromJSON(jsonValue));
    }

    /**
     * Register a new embedding provider that can be used to generate vector embeddings for text columns. Providers can be service-based (e.g., OpenAI) or local.
     * Create embedding provider
     */
    async createEmbeddingProvider(requestParameters: CreateEmbeddingProviderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEmbeddingProviderResponse> {
        const response = await this.createEmbeddingProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEmbeddingProvider without sending the request
     */
    async deleteEmbeddingProviderRequestOpts(requestParameters: DeleteEmbeddingProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEmbeddingProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/embedding-providers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete embedding provider
     */
    async deleteEmbeddingProviderRaw(requestParameters: DeleteEmbeddingProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteEmbeddingProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete embedding provider
     */
    async deleteEmbeddingProvider(requestParameters: DeleteEmbeddingProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEmbeddingProviderRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getEmbeddingProvider without sending the request
     */
    async getEmbeddingProviderRequestOpts(requestParameters: GetEmbeddingProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmbeddingProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/embedding-providers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get embedding provider
     */
    async getEmbeddingProviderRaw(requestParameters: GetEmbeddingProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmbeddingProviderResponse>> {
        const requestOptions = await this.getEmbeddingProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmbeddingProviderResponseFromJSON(jsonValue));
    }

    /**
     * Get embedding provider
     */
    async getEmbeddingProvider(requestParameters: GetEmbeddingProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmbeddingProviderResponse> {
        const response = await this.getEmbeddingProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listEmbeddingProviders without sending the request
     */
    async listEmbeddingProvidersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/embedding-providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all registered embedding providers.
     * List embedding providers
     */
    async listEmbeddingProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEmbeddingProvidersResponse>> {
        const requestOptions = await this.listEmbeddingProvidersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEmbeddingProvidersResponseFromJSON(jsonValue));
    }

    /**
     * List all registered embedding providers.
     * List embedding providers
     */
    async listEmbeddingProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEmbeddingProvidersResponse> {
        const response = await this.listEmbeddingProvidersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEmbeddingProvider without sending the request
     */
    async updateEmbeddingProviderRequestOpts(requestParameters: UpdateEmbeddingProviderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEmbeddingProvider().'
            );
        }

        if (requestParameters['updateEmbeddingProviderRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEmbeddingProviderRequest',
                'Required parameter "updateEmbeddingProviderRequest" was null or undefined when calling updateEmbeddingProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/embedding-providers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEmbeddingProviderRequestToJSON(requestParameters['updateEmbeddingProviderRequest']),
        };
    }

    /**
     * Update embedding provider
     */
    async updateEmbeddingProviderRaw(requestParameters: UpdateEmbeddingProviderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateEmbeddingProviderResponse>> {
        const requestOptions = await this.updateEmbeddingProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateEmbeddingProviderResponseFromJSON(jsonValue));
    }

    /**
     * Update embedding provider
     */
    async updateEmbeddingProvider(requestParameters: UpdateEmbeddingProviderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateEmbeddingProviderResponse> {
        const response = await this.updateEmbeddingProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
