/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  InformationSchemaResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    InformationSchemaResponseFromJSON,
    InformationSchemaResponseToJSON,
} from '../models/index';

export interface InformationSchemaRequest {
    connectionId?: string;
    schema?: string;
    table?: string;
    includeColumns?: boolean;
    limit?: number;
    cursor?: string;
}

/**
 * 
 */
export class InformationSchemaApi extends runtime.BaseAPI {

    /**
     * Creates request options for informationSchema without sending the request
     */
    async informationSchemaRequestOpts(requestParameters: InformationSchemaRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['connectionId'] != null) {
            queryParameters['connection_id'] = requestParameters['connectionId'];
        }

        if (requestParameters['schema'] != null) {
            queryParameters['schema'] = requestParameters['schema'];
        }

        if (requestParameters['table'] != null) {
            queryParameters['table'] = requestParameters['table'];
        }

        if (requestParameters['includeColumns'] != null) {
            queryParameters['include_columns'] = requestParameters['includeColumns'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/information_schema`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List discovered tables with optional filtering and pagination. Supports wildcard patterns (SQL %) for schema and table name filters. Set include_columns=true to include column definitions (omitted by default).
     * List tables
     */
    async informationSchemaRaw(requestParameters: InformationSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InformationSchemaResponse>> {
        const requestOptions = await this.informationSchemaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InformationSchemaResponseFromJSON(jsonValue));
    }

    /**
     * List discovered tables with optional filtering and pagination. Supports wildcard patterns (SQL %) for schema and table name filters. Set include_columns=true to include column definitions (omitted by default).
     * List tables
     */
    async informationSchema(requestParameters: InformationSchemaRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InformationSchemaResponse> {
        const response = await this.informationSchemaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
