/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  ListQueryRunsResponse,
  QueryRunInfo,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ListQueryRunsResponseFromJSON,
    ListQueryRunsResponseToJSON,
    QueryRunInfoFromJSON,
    QueryRunInfoToJSON,
} from '../models/index';

export interface GetQueryRunRequest {
    id: string;
}

export interface ListQueryRunsRequest {
    limit?: number;
    cursor?: string;
    status?: string;
    savedQueryId?: string;
}

/**
 * 
 */
export class QueryRunsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getQueryRun without sending the request
     */
    async getQueryRunRequestOpts(requestParameters: GetQueryRunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getQueryRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/query-runs/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the status and details of a specific query run by ID.
     * Get query run
     */
    async getQueryRunRaw(requestParameters: GetQueryRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryRunInfo>> {
        const requestOptions = await this.getQueryRunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryRunInfoFromJSON(jsonValue));
    }

    /**
     * Get the status and details of a specific query run by ID.
     * Get query run
     */
    async getQueryRun(requestParameters: GetQueryRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryRunInfo> {
        const response = await this.getQueryRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listQueryRuns without sending the request
     */
    async listQueryRunsRequestOpts(requestParameters: ListQueryRunsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['savedQueryId'] != null) {
            queryParameters['saved_query_id'] = requestParameters['savedQueryId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/query-runs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List query runs
     */
    async listQueryRunsRaw(requestParameters: ListQueryRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListQueryRunsResponse>> {
        const requestOptions = await this.listQueryRunsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListQueryRunsResponseFromJSON(jsonValue));
    }

    /**
     * List query runs
     */
    async listQueryRuns(requestParameters: ListQueryRunsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListQueryRunsResponse> {
        const response = await this.listQueryRunsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
