/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListQueryRunsResponse,
} from '../models/index';
import {
    ListQueryRunsResponseFromJSON,
    ListQueryRunsResponseToJSON,
} from '../models/index';

export interface ListQueryRunsRequest {
    limit?: number;
    cursor?: string;
}

/**
 * 
 */
export class QueryRunsApi extends runtime.BaseAPI {

    /**
     * Creates request options for listQueryRuns without sending the request
     */
    async listQueryRunsRequestOpts(requestParameters: ListQueryRunsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/query-runs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List query runs
     */
    async listQueryRunsRaw(requestParameters: ListQueryRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListQueryRunsResponse>> {
        const requestOptions = await this.listQueryRunsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListQueryRunsResponseFromJSON(jsonValue));
    }

    /**
     * List query runs
     */
    async listQueryRuns(requestParameters: ListQueryRunsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListQueryRunsResponse> {
        const response = await this.listQueryRunsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
