/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  GetResultResponse,
  ListResultsResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    GetResultResponseFromJSON,
    GetResultResponseToJSON,
    ListResultsResponseFromJSON,
    ListResultsResponseToJSON,
} from '../models/index';

export interface GetResultRequest {
    id: string;
}

export interface ListResultsRequest {
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class ResultsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getResult without sending the request
     */
    async getResultRequestOpts(requestParameters: GetResultRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/results/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a persisted query result by ID. If the result is still being processed, only the status is returned. Once ready, the full column and row data is included in the response.
     * Get result
     */
    async getResultRaw(requestParameters: GetResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetResultResponse>> {
        const requestOptions = await this.getResultRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetResultResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a persisted query result by ID. If the result is still being processed, only the status is returned. Once ready, the full column and row data is included in the response.
     * Get result
     */
    async getResult(requestParameters: GetResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetResultResponse> {
        const response = await this.getResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listResults without sending the request
     */
    async listResultsRequestOpts(requestParameters: ListResultsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/results`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List results
     */
    async listResultsRaw(requestParameters: ListResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResultsResponse>> {
        const requestOptions = await this.listResultsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResultsResponseFromJSON(jsonValue));
    }

    /**
     * List results
     */
    async listResults(requestParameters: ListResultsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResultsResponse> {
        const response = await this.listResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
