/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSandboxRequest,
  DeleteSandboxResponse,
  ListSandboxesResponse,
  SandboxResponse,
  UpdateSandboxRequest,
} from '../models/index';
import {
    CreateSandboxRequestFromJSON,
    CreateSandboxRequestToJSON,
    DeleteSandboxResponseFromJSON,
    DeleteSandboxResponseToJSON,
    ListSandboxesResponseFromJSON,
    ListSandboxesResponseToJSON,
    SandboxResponseFromJSON,
    SandboxResponseToJSON,
    UpdateSandboxRequestFromJSON,
    UpdateSandboxRequestToJSON,
} from '../models/index';

export interface CreateSandboxOperationRequest {
    createSandboxRequest: CreateSandboxRequest;
}

export interface DeleteSandboxRequest {
    publicId: string;
}

export interface GetSandboxRequest {
    publicId: string;
}

export interface UpdateSandboxOperationRequest {
    publicId: string;
    updateSandboxRequest: UpdateSandboxRequest;
}

/**
 * 
 */
export class SandboxesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSandbox without sending the request
     */
    async createSandboxRequestOpts(requestParameters: CreateSandboxOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSandboxRequest'] == null) {
            throw new runtime.RequiredError(
                'createSandboxRequest',
                'Required parameter "createSandboxRequest" was null or undefined when calling createSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sandboxes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSandboxRequestToJSON(requestParameters['createSandboxRequest']),
        };
    }

    /**
     * Creates a sandbox in the requested workspace. The returned `public_id` is the value to pass as `X-Session-Id` on scoped ops.
     * Create a sandbox
     */
    async createSandboxRaw(requestParameters: CreateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxResponse>> {
        const requestOptions = await this.createSandboxRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxResponseFromJSON(jsonValue));
    }

    /**
     * Creates a sandbox in the requested workspace. The returned `public_id` is the value to pass as `X-Session-Id` on scoped ops.
     * Create a sandbox
     */
    async createSandbox(requestParameters: CreateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxResponse> {
        const response = await this.createSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSandbox without sending the request
     */
    async deleteSandboxRequestOpts(requestParameters: DeleteSandboxRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['publicId'] == null) {
            throw new runtime.RequiredError(
                'publicId',
                'Required parameter "publicId" was null or undefined when calling deleteSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sandboxes/{public_id}`;
        urlPath = urlPath.replace(`{${"public_id"}}`, encodeURIComponent(String(requestParameters['publicId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete sandbox
     */
    async deleteSandboxRaw(requestParameters: DeleteSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteSandboxResponse>> {
        const requestOptions = await this.deleteSandboxRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteSandboxResponseFromJSON(jsonValue));
    }

    /**
     * Delete sandbox
     */
    async deleteSandbox(requestParameters: DeleteSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteSandboxResponse> {
        const response = await this.deleteSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSandbox without sending the request
     */
    async getSandboxRequestOpts(requestParameters: GetSandboxRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['publicId'] == null) {
            throw new runtime.RequiredError(
                'publicId',
                'Required parameter "publicId" was null or undefined when calling getSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sandboxes/{public_id}`;
        urlPath = urlPath.replace(`{${"public_id"}}`, encodeURIComponent(String(requestParameters['publicId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get sandbox
     */
    async getSandboxRaw(requestParameters: GetSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxResponse>> {
        const requestOptions = await this.getSandboxRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxResponseFromJSON(jsonValue));
    }

    /**
     * Get sandbox
     */
    async getSandbox(requestParameters: GetSandboxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxResponse> {
        const response = await this.getSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSandboxes without sending the request
     */
    async listSandboxesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sandboxes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists sandboxes for the caller in the requested workspace.
     * List sandboxes
     */
    async listSandboxesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSandboxesResponse>> {
        const requestOptions = await this.listSandboxesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSandboxesResponseFromJSON(jsonValue));
    }

    /**
     * Lists sandboxes for the caller in the requested workspace.
     * List sandboxes
     */
    async listSandboxes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSandboxesResponse> {
        const response = await this.listSandboxesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSandbox without sending the request
     */
    async updateSandboxRequestOpts(requestParameters: UpdateSandboxOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['publicId'] == null) {
            throw new runtime.RequiredError(
                'publicId',
                'Required parameter "publicId" was null or undefined when calling updateSandbox().'
            );
        }

        if (requestParameters['updateSandboxRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSandboxRequest',
                'Required parameter "updateSandboxRequest" was null or undefined when calling updateSandbox().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sandboxes/{public_id}`;
        urlPath = urlPath.replace(`{${"public_id"}}`, encodeURIComponent(String(requestParameters['publicId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSandboxRequestToJSON(requestParameters['updateSandboxRequest']),
        };
    }

    /**
     * Partial update. Only the provided fields are changed.
     * Update sandbox
     */
    async updateSandboxRaw(requestParameters: UpdateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SandboxResponse>> {
        const requestOptions = await this.updateSandboxRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SandboxResponseFromJSON(jsonValue));
    }

    /**
     * Partial update. Only the provided fields are changed.
     * Update sandbox
     */
    async updateSandbox(requestParameters: UpdateSandboxOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SandboxResponse> {
        const response = await this.updateSandboxRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
