/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CreateSavedQueryRequest,
  ExecuteSavedQueryRequest,
  ListSavedQueriesResponse,
  ListSavedQueryVersionsResponse,
  QueryResponse,
  SavedQueryDetail,
  UpdateSavedQueryRequest,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CreateSavedQueryRequestFromJSON,
    CreateSavedQueryRequestToJSON,
    ExecuteSavedQueryRequestFromJSON,
    ExecuteSavedQueryRequestToJSON,
    ListSavedQueriesResponseFromJSON,
    ListSavedQueriesResponseToJSON,
    ListSavedQueryVersionsResponseFromJSON,
    ListSavedQueryVersionsResponseToJSON,
    QueryResponseFromJSON,
    QueryResponseToJSON,
    SavedQueryDetailFromJSON,
    SavedQueryDetailToJSON,
    UpdateSavedQueryRequestFromJSON,
    UpdateSavedQueryRequestToJSON,
} from '../models/index';

export interface CreateSavedQueryOperationRequest {
    createSavedQueryRequest: CreateSavedQueryRequest;
}

export interface DeleteSavedQueryRequest {
    id: string;
}

export interface ExecuteSavedQueryOperationRequest {
    id: string;
    executeSavedQueryRequest?: ExecuteSavedQueryRequest | null;
}

export interface GetSavedQueryRequest {
    id: string;
}

export interface ListSavedQueriesRequest {
    limit?: number;
    offset?: number;
}

export interface ListSavedQueryVersionsRequest {
    id: string;
    limit?: number;
    offset?: number;
}

export interface UpdateSavedQueryOperationRequest {
    id: string;
    updateSavedQueryRequest: UpdateSavedQueryRequest;
}

/**
 * 
 */
export class SavedQueriesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSavedQuery without sending the request
     */
    async createSavedQueryRequestOpts(requestParameters: CreateSavedQueryOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSavedQueryRequest'] == null) {
            throw new runtime.RequiredError(
                'createSavedQueryRequest',
                'Required parameter "createSavedQueryRequest" was null or undefined when calling createSavedQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSavedQueryRequestToJSON(requestParameters['createSavedQueryRequest']),
        };
    }

    /**
     * Save a named SQL query. The SQL is stored as version 1 and automatically analyzed for classification metadata (category, table count, predicate/join/aggregation flags).
     * Create saved query
     */
    async createSavedQueryRaw(requestParameters: CreateSavedQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedQueryDetail>> {
        const requestOptions = await this.createSavedQueryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavedQueryDetailFromJSON(jsonValue));
    }

    /**
     * Save a named SQL query. The SQL is stored as version 1 and automatically analyzed for classification metadata (category, table count, predicate/join/aggregation flags).
     * Create saved query
     */
    async createSavedQuery(requestParameters: CreateSavedQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedQueryDetail> {
        const response = await this.createSavedQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSavedQuery without sending the request
     */
    async deleteSavedQueryRequestOpts(requestParameters: DeleteSavedQueryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSavedQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete saved query
     */
    async deleteSavedQueryRaw(requestParameters: DeleteSavedQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSavedQueryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete saved query
     */
    async deleteSavedQuery(requestParameters: DeleteSavedQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSavedQueryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for executeSavedQuery without sending the request
     */
    async executeSavedQueryRequestOpts(requestParameters: ExecuteSavedQueryOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling executeSavedQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries/{id}/execute`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecuteSavedQueryRequestToJSON(requestParameters['executeSavedQueryRequest']),
        };
    }

    /**
     * Execute a saved query. By default runs the latest version. Optionally specify a version number to execute a previous version. Returns the same response format as POST /v1/query.
     * Execute saved query
     */
    async executeSavedQueryRaw(requestParameters: ExecuteSavedQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponse>> {
        const requestOptions = await this.executeSavedQueryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseFromJSON(jsonValue));
    }

    /**
     * Execute a saved query. By default runs the latest version. Optionally specify a version number to execute a previous version. Returns the same response format as POST /v1/query.
     * Execute saved query
     */
    async executeSavedQuery(requestParameters: ExecuteSavedQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponse> {
        const response = await this.executeSavedQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSavedQuery without sending the request
     */
    async getSavedQueryRequestOpts(requestParameters: GetSavedQueryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSavedQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get saved query
     */
    async getSavedQueryRaw(requestParameters: GetSavedQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedQueryDetail>> {
        const requestOptions = await this.getSavedQueryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavedQueryDetailFromJSON(jsonValue));
    }

    /**
     * Get saved query
     */
    async getSavedQuery(requestParameters: GetSavedQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedQueryDetail> {
        const response = await this.getSavedQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSavedQueries without sending the request
     */
    async listSavedQueriesRequestOpts(requestParameters: ListSavedQueriesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List saved queries
     */
    async listSavedQueriesRaw(requestParameters: ListSavedQueriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSavedQueriesResponse>> {
        const requestOptions = await this.listSavedQueriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSavedQueriesResponseFromJSON(jsonValue));
    }

    /**
     * List saved queries
     */
    async listSavedQueries(requestParameters: ListSavedQueriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSavedQueriesResponse> {
        const response = await this.listSavedQueriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSavedQueryVersions without sending the request
     */
    async listSavedQueryVersionsRequestOpts(requestParameters: ListSavedQueryVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listSavedQueryVersions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries/{id}/versions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List saved query versions
     */
    async listSavedQueryVersionsRaw(requestParameters: ListSavedQueryVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSavedQueryVersionsResponse>> {
        const requestOptions = await this.listSavedQueryVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSavedQueryVersionsResponseFromJSON(jsonValue));
    }

    /**
     * List saved query versions
     */
    async listSavedQueryVersions(requestParameters: ListSavedQueryVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSavedQueryVersionsResponse> {
        const response = await this.listSavedQueryVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSavedQuery without sending the request
     */
    async updateSavedQueryRequestOpts(requestParameters: UpdateSavedQueryOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSavedQuery().'
            );
        }

        if (requestParameters['updateSavedQueryRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSavedQueryRequest',
                'Required parameter "updateSavedQueryRequest" was null or undefined when calling updateSavedQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSavedQueryRequestToJSON(requestParameters['updateSavedQueryRequest']),
        };
    }

    /**
     * Update a saved query. If the SQL changes, a new version is created (previous versions are preserved). Name, tags, description, and classification overrides can also be updated.
     * Update saved query
     */
    async updateSavedQueryRaw(requestParameters: UpdateSavedQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedQueryDetail>> {
        const requestOptions = await this.updateSavedQueryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavedQueryDetailFromJSON(jsonValue));
    }

    /**
     * Update a saved query. If the SQL changes, a new version is created (previous versions are preserved). Name, tags, description, and classification overrides can also be updated.
     * Update saved query
     */
    async updateSavedQuery(requestParameters: UpdateSavedQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedQueryDetail> {
        const response = await this.updateSavedQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
