/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CreateSecretRequest,
  CreateSecretResponse,
  GetSecretResponse,
  ListSecretsResponse,
  UpdateSecretRequest,
  UpdateSecretResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CreateSecretRequestFromJSON,
    CreateSecretRequestToJSON,
    CreateSecretResponseFromJSON,
    CreateSecretResponseToJSON,
    GetSecretResponseFromJSON,
    GetSecretResponseToJSON,
    ListSecretsResponseFromJSON,
    ListSecretsResponseToJSON,
    UpdateSecretRequestFromJSON,
    UpdateSecretRequestToJSON,
    UpdateSecretResponseFromJSON,
    UpdateSecretResponseToJSON,
} from '../models/index';

export interface CreateSecretOperationRequest {
    createSecretRequest: CreateSecretRequest;
}

export interface DeleteSecretRequest {
    name: string;
}

export interface GetSecretRequest {
    name: string;
}

export interface UpdateSecretOperationRequest {
    name: string;
    updateSecretRequest: UpdateSecretRequest;
}

/**
 * 
 */
export class SecretsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSecret without sending the request
     */
    async createSecretRequestOpts(requestParameters: CreateSecretOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSecretRequest'] == null) {
            throw new runtime.RequiredError(
                'createSecretRequest',
                'Required parameter "createSecretRequest" was null or undefined when calling createSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/secrets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSecretRequestToJSON(requestParameters['createSecretRequest']),
        };
    }

    /**
     * Store a new named secret. The value is encrypted at rest and can be referenced by connections for authentication. Secret names must be unique.
     * Create secret
     */
    async createSecretRaw(requestParameters: CreateSecretOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSecretResponse>> {
        const requestOptions = await this.createSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSecretResponseFromJSON(jsonValue));
    }

    /**
     * Store a new named secret. The value is encrypted at rest and can be referenced by connections for authentication. Secret names must be unique.
     * Create secret
     */
    async createSecret(requestParameters: CreateSecretOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSecretResponse> {
        const response = await this.createSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSecret without sending the request
     */
    async deleteSecretRequestOpts(requestParameters: DeleteSecretRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/secrets/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete secret
     */
    async deleteSecretRaw(requestParameters: DeleteSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete secret
     */
    async deleteSecret(requestParameters: DeleteSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSecretRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getSecret without sending the request
     */
    async getSecretRequestOpts(requestParameters: GetSecretRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/secrets/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get metadata for a secret. The secret value is never returned.
     * Get secret
     */
    async getSecretRaw(requestParameters: GetSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSecretResponse>> {
        const requestOptions = await this.getSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSecretResponseFromJSON(jsonValue));
    }

    /**
     * Get metadata for a secret. The secret value is never returned.
     * Get secret
     */
    async getSecret(requestParameters: GetSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSecretResponse> {
        const response = await this.getSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSecrets without sending the request
     */
    async listSecretsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/secrets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all stored secrets. Only metadata (name, timestamps) is returned — secret values are never exposed.
     * List secrets
     */
    async listSecretsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSecretsResponse>> {
        const requestOptions = await this.listSecretsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSecretsResponseFromJSON(jsonValue));
    }

    /**
     * List all stored secrets. Only metadata (name, timestamps) is returned — secret values are never exposed.
     * List secrets
     */
    async listSecrets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSecretsResponse> {
        const response = await this.listSecretsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSecret without sending the request
     */
    async updateSecretRequestOpts(requestParameters: UpdateSecretOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling updateSecret().'
            );
        }

        if (requestParameters['updateSecretRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSecretRequest',
                'Required parameter "updateSecretRequest" was null or undefined when calling updateSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Workspace-Id"] = await this.configuration.apiKey("X-Workspace-Id"); // WorkspaceId authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/secrets/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSecretRequestToJSON(requestParameters['updateSecretRequest']),
        };
    }

    /**
     * Update secret
     */
    async updateSecretRaw(requestParameters: UpdateSecretOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateSecretResponse>> {
        const requestOptions = await this.updateSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateSecretResponseFromJSON(jsonValue));
    }

    /**
     * Update secret
     */
    async updateSecret(requestParameters: UpdateSecretOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateSecretResponse> {
        const response = await this.updateSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
