/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response returned when a query is submitted asynchronously (202 Accepted).
 * 
 * Poll GET /query-runs/{id} to track progress. Once status is "succeeded",
 * retrieve results via GET /results/{result_id}.
 * @export
 * @interface AsyncQueryResponse
 */
export interface AsyncQueryResponse {
    /**
     * Unique identifier for the query run.
     * @type {string}
     * @memberof AsyncQueryResponse
     */
    queryRunId: string;
    /**
     * Human-readable reason why the query went async (e.g., caching tables for the first time).
     * @type {string}
     * @memberof AsyncQueryResponse
     */
    reason?: string | null;
    /**
     * Current status of the query run.
     * @type {string}
     * @memberof AsyncQueryResponse
     */
    status: string;
    /**
     * URL to poll for query run status.
     * @type {string}
     * @memberof AsyncQueryResponse
     */
    statusUrl: string;
}

/**
 * Check if a given object implements the AsyncQueryResponse interface.
 */
export function instanceOfAsyncQueryResponse(value: object): value is AsyncQueryResponse {
    if (!('queryRunId' in value) || value['queryRunId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusUrl' in value) || value['statusUrl'] === undefined) return false;
    return true;
}

export function AsyncQueryResponseFromJSON(json: any): AsyncQueryResponse {
    return AsyncQueryResponseFromJSONTyped(json, false);
}

export function AsyncQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'queryRunId': json['query_run_id'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'status': json['status'],
        'statusUrl': json['status_url'],
    };
}

export function AsyncQueryResponseToJSON(json: any): AsyncQueryResponse {
    return AsyncQueryResponseToJSONTyped(json, false);
}

export function AsyncQueryResponseToJSONTyped(value?: AsyncQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query_run_id': value['queryRunId'],
        'reason': value['reason'],
        'status': value['status'],
        'status_url': value['statusUrl'],
    };
}

