/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Boolean column.
 * @export
 * @interface BooleanProfileDetail
 */
export interface BooleanProfileDetail {
    /**
     * Number of false values
     * @type {number}
     * @memberof BooleanProfileDetail
     */
    falseCount: number;
    /**
     * Number of true values
     * @type {number}
     * @memberof BooleanProfileDetail
     */
    trueCount: number;
}

/**
 * Check if a given object implements the BooleanProfileDetail interface.
 */
export function instanceOfBooleanProfileDetail(value: object): value is BooleanProfileDetail {
    if (!('falseCount' in value) || value['falseCount'] === undefined) return false;
    if (!('trueCount' in value) || value['trueCount'] === undefined) return false;
    return true;
}

export function BooleanProfileDetailFromJSON(json: any): BooleanProfileDetail {
    return BooleanProfileDetailFromJSONTyped(json, false);
}

export function BooleanProfileDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanProfileDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'falseCount': json['false_count'],
        'trueCount': json['true_count'],
    };
}

export function BooleanProfileDetailToJSON(json: any): BooleanProfileDetail {
    return BooleanProfileDetailToJSONTyped(json, false);
}

export function BooleanProfileDetailToJSONTyped(value?: BooleanProfileDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'false_count': value['falseCount'],
        'true_count': value['trueCount'],
    };
}

