/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryValueInfo } from './CategoryValueInfo';
import {
    CategoryValueInfoFromJSON,
    CategoryValueInfoFromJSONTyped,
    CategoryValueInfoToJSON,
    CategoryValueInfoToJSONTyped,
} from './CategoryValueInfo';

/**
 * Type-specific column profile detail. The `type` discriminator field determines which
 * variant is present. Profile type is chosen based on the column's Arrow data type and
 * cardinality:
 * 
 * - **categorical**: Text or numeric columns with ≤200 distinct values. Lists each value with its frequency.
 * - **text**: Text columns with >200 distinct values. Reports string length statistics.
 * - **numeric**: Numeric columns with >200 distinct values. Reports min, max, and mean.
 * - **temporal**: Date and timestamp columns. Reports min and max as ISO-8601 strings.
 * - **boolean**: Boolean columns. Reports true and false counts.
 *   Low-cardinality column (≤200 distinct values). Values sorted by frequency descending.
 * @export
 * @interface CategoricalProfileDetail
 */
export interface CategoricalProfileDetail {
    /**
     * Distinct values with their counts, ordered by count descending
     * @type {Array<CategoryValueInfo>}
     * @memberof CategoricalProfileDetail
     */
    values: Array<CategoryValueInfo>;
}

/**
 * Check if a given object implements the CategoricalProfileDetail interface.
 */
export function instanceOfCategoricalProfileDetail(value: object): value is CategoricalProfileDetail {
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function CategoricalProfileDetailFromJSON(json: any): CategoricalProfileDetail {
    return CategoricalProfileDetailFromJSONTyped(json, false);
}

export function CategoricalProfileDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoricalProfileDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'values': ((json['values'] as Array<any>).map(CategoryValueInfoFromJSON)),
    };
}

export function CategoricalProfileDetailToJSON(json: any): CategoricalProfileDetail {
    return CategoricalProfileDetailToJSONTyped(json, false);
}

export function CategoricalProfileDetailToJSONTyped(value?: CategoricalProfileDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': ((value['values'] as Array<any>).map(CategoryValueInfoToJSON)),
    };
}

