/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A distinct value with its frequency count, used in categorical profiles.
 * @export
 * @interface CategoryValueInfo
 */
export interface CategoryValueInfo {
    /**
     * Number of occurrences
     * @type {number}
     * @memberof CategoryValueInfo
     */
    count: number;
    /**
     * The distinct value (as a string, or null)
     * @type {string}
     * @memberof CategoryValueInfo
     */
    value?: string | null;
}

/**
 * Check if a given object implements the CategoryValueInfo interface.
 */
export function instanceOfCategoryValueInfo(value: object): value is CategoryValueInfo {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function CategoryValueInfoFromJSON(json: any): CategoryValueInfo {
    return CategoryValueInfoFromJSONTyped(json, false);
}

export function CategoryValueInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryValueInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function CategoryValueInfoToJSON(json: any): CategoryValueInfo {
    return CategoryValueInfoToJSONTyped(json, false);
}

export function CategoryValueInfoToJSONTyped(value?: CategoryValueInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'value': value['value'],
    };
}

