/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColumnProfileDetailOneOf3
 */
export interface ColumnProfileDetailOneOf3 {
    /**
     * Latest value as ISO-8601 string
     * @type {string}
     * @memberof ColumnProfileDetailOneOf3
     */
    max: string;
    /**
     * Earliest value as ISO-8601 string
     * @type {string}
     * @memberof ColumnProfileDetailOneOf3
     */
    min: string;
    /**
     * 
     * @type {ColumnProfileDetailOneOf3TypeEnum}
     * @memberof ColumnProfileDetailOneOf3
     */
    type: ColumnProfileDetailOneOf3TypeEnum;
}


/**
 * @export
 */
export const ColumnProfileDetailOneOf3TypeEnum = {
    Temporal: 'temporal'
} as const;
export type ColumnProfileDetailOneOf3TypeEnum = typeof ColumnProfileDetailOneOf3TypeEnum[keyof typeof ColumnProfileDetailOneOf3TypeEnum];


/**
 * Check if a given object implements the ColumnProfileDetailOneOf3 interface.
 */
export function instanceOfColumnProfileDetailOneOf3(value: object): value is ColumnProfileDetailOneOf3 {
    if (!('max' in value) || value['max'] === undefined) return false;
    if (!('min' in value) || value['min'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ColumnProfileDetailOneOf3FromJSON(json: any): ColumnProfileDetailOneOf3 {
    return ColumnProfileDetailOneOf3FromJSONTyped(json, false);
}

export function ColumnProfileDetailOneOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnProfileDetailOneOf3 {
    if (json == null) {
        return json;
    }
    return {
        
        'max': json['max'],
        'min': json['min'],
        'type': json['type'],
    };
}

export function ColumnProfileDetailOneOf3ToJSON(json: any): ColumnProfileDetailOneOf3 {
    return ColumnProfileDetailOneOf3ToJSONTyped(json, false);
}

export function ColumnProfileDetailOneOf3ToJSONTyped(value?: ColumnProfileDetailOneOf3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max': value['max'],
        'min': value['min'],
        'type': value['type'],
    };
}

