/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ColumnProfileDetailOneOf } from './ColumnProfileDetailOneOf';
import {
    instanceOfColumnProfileDetailOneOf,
    ColumnProfileDetailOneOfFromJSON,
    ColumnProfileDetailOneOfFromJSONTyped,
    ColumnProfileDetailOneOfToJSON,
} from './ColumnProfileDetailOneOf';
import type { ColumnProfileDetailOneOf1 } from './ColumnProfileDetailOneOf1';
import {
    instanceOfColumnProfileDetailOneOf1,
    ColumnProfileDetailOneOf1FromJSON,
    ColumnProfileDetailOneOf1FromJSONTyped,
    ColumnProfileDetailOneOf1ToJSON,
} from './ColumnProfileDetailOneOf1';
import type { ColumnProfileDetailOneOf2 } from './ColumnProfileDetailOneOf2';
import {
    instanceOfColumnProfileDetailOneOf2,
    ColumnProfileDetailOneOf2FromJSON,
    ColumnProfileDetailOneOf2FromJSONTyped,
    ColumnProfileDetailOneOf2ToJSON,
} from './ColumnProfileDetailOneOf2';
import type { ColumnProfileDetailOneOf3 } from './ColumnProfileDetailOneOf3';
import {
    instanceOfColumnProfileDetailOneOf3,
    ColumnProfileDetailOneOf3FromJSON,
    ColumnProfileDetailOneOf3FromJSONTyped,
    ColumnProfileDetailOneOf3ToJSON,
} from './ColumnProfileDetailOneOf3';
import type { ColumnProfileDetailOneOf4 } from './ColumnProfileDetailOneOf4';
import {
    instanceOfColumnProfileDetailOneOf4,
    ColumnProfileDetailOneOf4FromJSON,
    ColumnProfileDetailOneOf4FromJSONTyped,
    ColumnProfileDetailOneOf4ToJSON,
} from './ColumnProfileDetailOneOf4';

/**
 * @type ColumnProfileDetail
 * Type-specific column profile detail. The `type` discriminator field determines which
 * variant is present. Profile type is chosen based on the column's Arrow data type and
 * cardinality:
 * 
 * - **categorical**: Text or numeric columns with ≤200 distinct values. Lists each value with its frequency.
 * - **text**: Text columns with >200 distinct values. Reports string length statistics.
 * - **numeric**: Numeric columns with >200 distinct values. Reports min, max, and mean.
 * - **temporal**: Date and timestamp columns. Reports min and max as ISO-8601 strings.
 * - **boolean**: Boolean columns. Reports true and false counts.
 * @export
 */
export type ColumnProfileDetail = ColumnProfileDetailOneOf | ColumnProfileDetailOneOf1 | ColumnProfileDetailOneOf2 | ColumnProfileDetailOneOf3 | ColumnProfileDetailOneOf4;

export function ColumnProfileDetailFromJSON(json: any): ColumnProfileDetail {
    return ColumnProfileDetailFromJSONTyped(json, false);
}

export function ColumnProfileDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnProfileDetail {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfColumnProfileDetailOneOf(json)) {
        return ColumnProfileDetailOneOfFromJSONTyped(json, true);
    }
    if (instanceOfColumnProfileDetailOneOf1(json)) {
        return ColumnProfileDetailOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfColumnProfileDetailOneOf2(json)) {
        return ColumnProfileDetailOneOf2FromJSONTyped(json, true);
    }
    if (instanceOfColumnProfileDetailOneOf3(json)) {
        return ColumnProfileDetailOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfColumnProfileDetailOneOf4(json)) {
        return ColumnProfileDetailOneOf4FromJSONTyped(json, true);
    }
    return {} as any;
}

export function ColumnProfileDetailToJSON(json: any): any {
    return ColumnProfileDetailToJSONTyped(json, false);
}

export function ColumnProfileDetailToJSONTyped(value?: ColumnProfileDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfColumnProfileDetailOneOf(value)) {
        return ColumnProfileDetailOneOfToJSON(value as ColumnProfileDetailOneOf);
    }
    if (instanceOfColumnProfileDetailOneOf1(value)) {
        return ColumnProfileDetailOneOf1ToJSON(value as ColumnProfileDetailOneOf1);
    }
    if (instanceOfColumnProfileDetailOneOf2(value)) {
        return ColumnProfileDetailOneOf2ToJSON(value as ColumnProfileDetailOneOf2);
    }
    if (instanceOfColumnProfileDetailOneOf3(value)) {
        return ColumnProfileDetailOneOf3ToJSON(value as ColumnProfileDetailOneOf3);
    }
    if (instanceOfColumnProfileDetailOneOf4(value)) {
        return ColumnProfileDetailOneOf4ToJSON(value as ColumnProfileDetailOneOf4);
    }
    return {};
}

