/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * High-cardinality text column (>200 distinct values).
 * @export
 * @interface ColumnProfileDetailOneOf1
 */
export interface ColumnProfileDetailOneOf1 {
    /**
     * Average string length
     * @type {number}
     * @memberof ColumnProfileDetailOneOf1
     */
    avgLength: number;
    /**
     * Longest string length in the column
     * @type {number}
     * @memberof ColumnProfileDetailOneOf1
     */
    maxLength: number;
    /**
     * Shortest string length in the column
     * @type {number}
     * @memberof ColumnProfileDetailOneOf1
     */
    minLength: number;
    /**
     * 
     * @type {ColumnProfileDetailOneOf1TypeEnum}
     * @memberof ColumnProfileDetailOneOf1
     */
    type: ColumnProfileDetailOneOf1TypeEnum;
}


/**
 * @export
 */
export const ColumnProfileDetailOneOf1TypeEnum = {
    Text: 'text'
} as const;
export type ColumnProfileDetailOneOf1TypeEnum = typeof ColumnProfileDetailOneOf1TypeEnum[keyof typeof ColumnProfileDetailOneOf1TypeEnum];


/**
 * Check if a given object implements the ColumnProfileDetailOneOf1 interface.
 */
export function instanceOfColumnProfileDetailOneOf1(value: object): value is ColumnProfileDetailOneOf1 {
    if (!('avgLength' in value) || value['avgLength'] === undefined) return false;
    if (!('maxLength' in value) || value['maxLength'] === undefined) return false;
    if (!('minLength' in value) || value['minLength'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ColumnProfileDetailOneOf1FromJSON(json: any): ColumnProfileDetailOneOf1 {
    return ColumnProfileDetailOneOf1FromJSONTyped(json, false);
}

export function ColumnProfileDetailOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnProfileDetailOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'avgLength': json['avg_length'],
        'maxLength': json['max_length'],
        'minLength': json['min_length'],
        'type': json['type'],
    };
}

export function ColumnProfileDetailOneOf1ToJSON(json: any): ColumnProfileDetailOneOf1 {
    return ColumnProfileDetailOneOf1ToJSONTyped(json, false);
}

export function ColumnProfileDetailOneOf1ToJSONTyped(value?: ColumnProfileDetailOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_length': value['avgLength'],
        'max_length': value['maxLength'],
        'min_length': value['minLength'],
        'type': value['type'],
    };
}

