/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryValueInfo } from './CategoryValueInfo';
import {
    CategoryValueInfoFromJSON,
    CategoryValueInfoFromJSONTyped,
    CategoryValueInfoToJSON,
    CategoryValueInfoToJSONTyped,
} from './CategoryValueInfo';

/**
 * 
 * @export
 * @interface ColumnProfileDetailOneOf
 */
export interface ColumnProfileDetailOneOf {
    /**
     * Distinct values with their counts, ordered by count descending
     * @type {Array<CategoryValueInfo>}
     * @memberof ColumnProfileDetailOneOf
     */
    values: Array<CategoryValueInfo>;
    /**
     * 
     * @type {ColumnProfileDetailOneOfTypeEnum}
     * @memberof ColumnProfileDetailOneOf
     */
    type: ColumnProfileDetailOneOfTypeEnum;
}


/**
 * @export
 */
export const ColumnProfileDetailOneOfTypeEnum = {
    Categorical: 'categorical'
} as const;
export type ColumnProfileDetailOneOfTypeEnum = typeof ColumnProfileDetailOneOfTypeEnum[keyof typeof ColumnProfileDetailOneOfTypeEnum];


/**
 * Check if a given object implements the ColumnProfileDetailOneOf interface.
 */
export function instanceOfColumnProfileDetailOneOf(value: object): value is ColumnProfileDetailOneOf {
    if (!('values' in value) || value['values'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ColumnProfileDetailOneOfFromJSON(json: any): ColumnProfileDetailOneOf {
    return ColumnProfileDetailOneOfFromJSONTyped(json, false);
}

export function ColumnProfileDetailOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnProfileDetailOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'values': ((json['values'] as Array<any>).map(CategoryValueInfoFromJSON)),
        'type': json['type'],
    };
}

export function ColumnProfileDetailOneOfToJSON(json: any): ColumnProfileDetailOneOf {
    return ColumnProfileDetailOneOfToJSONTyped(json, false);
}

export function ColumnProfileDetailOneOfToJSONTyped(value?: ColumnProfileDetailOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': ((value['values'] as Array<any>).map(CategoryValueInfoToJSON)),
        'type': value['type'],
    };
}

