/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColumnProfileDetail } from './ColumnProfileDetail';
import {
    ColumnProfileDetailFromJSON,
    ColumnProfileDetailFromJSONTyped,
    ColumnProfileDetailToJSON,
    ColumnProfileDetailToJSONTyped,
} from './ColumnProfileDetail';

/**
 * Statistics for a single column.
 * @export
 * @interface ColumnProfileInfo
 */
export interface ColumnProfileInfo {
    /**
     * Approximate number of distinct non-null values
     * @type {number}
     * @memberof ColumnProfileInfo
     */
    cardinality: number;
    /**
     * Arrow data type (e.g. "Utf8", "Int32", "Timestamp(Microsecond, Some(\"UTC\"))")
     * @type {string}
     * @memberof ColumnProfileInfo
     */
    dataType: string;
    /**
     * Column name
     * @type {string}
     * @memberof ColumnProfileInfo
     */
    name: string;
    /**
     * Number of null values
     * @type {number}
     * @memberof ColumnProfileInfo
     */
    nullCount: number;
    /**
     * Percentage of null values (0.0 to 100.0)
     * @type {number}
     * @memberof ColumnProfileInfo
     */
    nullPercentage: number;
    /**
     * Type-specific profile detail. Null when the column is all-null or has an unsupported type.
     * @type {ColumnProfileDetail}
     * @memberof ColumnProfileInfo
     */
    profile?: ColumnProfileDetail | null;
}

/**
 * Check if a given object implements the ColumnProfileInfo interface.
 */
export function instanceOfColumnProfileInfo(value: object): value is ColumnProfileInfo {
    if (!('cardinality' in value) || value['cardinality'] === undefined) return false;
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nullCount' in value) || value['nullCount'] === undefined) return false;
    if (!('nullPercentage' in value) || value['nullPercentage'] === undefined) return false;
    return true;
}

export function ColumnProfileInfoFromJSON(json: any): ColumnProfileInfo {
    return ColumnProfileInfoFromJSONTyped(json, false);
}

export function ColumnProfileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnProfileInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'cardinality': json['cardinality'],
        'dataType': json['data_type'],
        'name': json['name'],
        'nullCount': json['null_count'],
        'nullPercentage': json['null_percentage'],
        'profile': json['profile'] == null ? undefined : ColumnProfileDetailFromJSON(json['profile']),
    };
}

export function ColumnProfileInfoToJSON(json: any): ColumnProfileInfo {
    return ColumnProfileInfoToJSONTyped(json, false);
}

export function ColumnProfileInfoToJSONTyped(value?: ColumnProfileInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cardinality': value['cardinality'],
        'data_type': value['dataType'],
        'name': value['name'],
        'null_count': value['nullCount'],
        'null_percentage': value['nullPercentage'],
        'profile': ColumnProfileDetailToJSON(value['profile']),
    };
}

