/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Column metadata for API responses
 * @export
 * @interface ColumnInfo
 */
export interface ColumnInfo {
    /**
     * 
     * @type {string}
     * @memberof ColumnInfo
     */
    dataType: string;
    /**
     * 
     * @type {string}
     * @memberof ColumnInfo
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ColumnInfo
     */
    nullable: boolean;
}

/**
 * Check if a given object implements the ColumnInfo interface.
 */
export function instanceOfColumnInfo(value: object): value is ColumnInfo {
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nullable' in value) || value['nullable'] === undefined) return false;
    return true;
}

export function ColumnInfoFromJSON(json: any): ColumnInfo {
    return ColumnInfoFromJSONTyped(json, false);
}

export function ColumnInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['data_type'],
        'name': json['name'],
        'nullable': json['nullable'],
    };
}

export function ColumnInfoToJSON(json: any): ColumnInfo {
    return ColumnInfoToJSONTyped(json, false);
}

export function ColumnInfoToJSONTyped(value?: ColumnInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type': value['dataType'],
        'name': value['name'],
        'nullable': value['nullable'],
    };
}

