/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Detailed column type specification with optional properties.
 * @export
 * @interface ColumnTypeSpec
 */
export interface ColumnTypeSpec {
    /**
     * Geometry type for GEOMETRY/GEOGRAPHY columns.
     * E.g., "Point", "LineString", "Polygon", "MultiPoint", "MultiLineString",
     * "MultiPolygon", "GeometryCollection", or "Geometry" (any).
     * @type {string}
     * @memberof ColumnTypeSpec
     */
    geometryType?: string | null;
    /**
     * Precision for DECIMAL type (1-38)
     * @type {number}
     * @memberof ColumnTypeSpec
     */
    precision?: number | null;
    /**
     * Scale for DECIMAL type
     * @type {number}
     * @memberof ColumnTypeSpec
     */
    scale?: number | null;
    /**
     * Spatial Reference System Identifier for GEOMETRY/GEOGRAPHY types.
     * Common values: 4326 (WGS84), 3857 (Web Mercator).
     * @type {number}
     * @memberof ColumnTypeSpec
     */
    srid?: number | null;
    /**
     * The data type name (e.g., "DECIMAL", "TIMESTAMP", "GEOMETRY")
     * @type {string}
     * @memberof ColumnTypeSpec
     */
    type: string;
}

/**
 * Check if a given object implements the ColumnTypeSpec interface.
 */
export function instanceOfColumnTypeSpec(value: object): value is ColumnTypeSpec {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ColumnTypeSpecFromJSON(json: any): ColumnTypeSpec {
    return ColumnTypeSpecFromJSONTyped(json, false);
}

export function ColumnTypeSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnTypeSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'geometryType': json['geometry_type'] == null ? undefined : json['geometry_type'],
        'precision': json['precision'] == null ? undefined : json['precision'],
        'scale': json['scale'] == null ? undefined : json['scale'],
        'srid': json['srid'] == null ? undefined : json['srid'],
        'type': json['type'],
    };
}

export function ColumnTypeSpecToJSON(json: any): ColumnTypeSpec {
    return ColumnTypeSpecToJSONTyped(json, false);
}

export function ColumnTypeSpecToJSONTyped(value?: ColumnTypeSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geometry_type': value['geometryType'],
        'precision': value['precision'],
        'scale': value['scale'],
        'srid': value['srid'],
        'type': value['type'],
    };
}

