/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Boolean column.
 * @export
 * @interface ColumnProfileDetailOneOf4
 */
export interface ColumnProfileDetailOneOf4 {
    /**
     * Number of false values
     * @type {number}
     * @memberof ColumnProfileDetailOneOf4
     */
    falseCount: number;
    /**
     * Number of true values
     * @type {number}
     * @memberof ColumnProfileDetailOneOf4
     */
    trueCount: number;
    /**
     * 
     * @type {ColumnProfileDetailOneOf4TypeEnum}
     * @memberof ColumnProfileDetailOneOf4
     */
    type: ColumnProfileDetailOneOf4TypeEnum;
}


/**
 * @export
 */
export const ColumnProfileDetailOneOf4TypeEnum = {
    Boolean: 'boolean'
} as const;
export type ColumnProfileDetailOneOf4TypeEnum = typeof ColumnProfileDetailOneOf4TypeEnum[keyof typeof ColumnProfileDetailOneOf4TypeEnum];


/**
 * Check if a given object implements the ColumnProfileDetailOneOf4 interface.
 */
export function instanceOfColumnProfileDetailOneOf4(value: object): value is ColumnProfileDetailOneOf4 {
    if (!('falseCount' in value) || value['falseCount'] === undefined) return false;
    if (!('trueCount' in value) || value['trueCount'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ColumnProfileDetailOneOf4FromJSON(json: any): ColumnProfileDetailOneOf4 {
    return ColumnProfileDetailOneOf4FromJSONTyped(json, false);
}

export function ColumnProfileDetailOneOf4FromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnProfileDetailOneOf4 {
    if (json == null) {
        return json;
    }
    return {
        
        'falseCount': json['false_count'],
        'trueCount': json['true_count'],
        'type': json['type'],
    };
}

export function ColumnProfileDetailOneOf4ToJSON(json: any): ColumnProfileDetailOneOf4 {
    return ColumnProfileDetailOneOf4ToJSONTyped(json, false);
}

export function ColumnProfileDetailOneOf4ToJSONTyped(value?: ColumnProfileDetailOneOf4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'false_count': value['falseCount'],
        'true_count': value['trueCount'],
        'type': value['type'],
    };
}

