/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ColumnDefinition
 * Column type specification - either a simple type string or detailed spec with properties.
 * 
 * Simple form: `"VARCHAR"`, `"INT"`, `"DATE"`
 * Detailed form: `{ "type": "DECIMAL", "precision": 10, "scale": 2 }`
 * @export
 */
export type ColumnDefinition = ColumnTypeSpec | string;

export function ColumnDefinitionFromJSON(json: any): ColumnDefinition {
    return ColumnDefinitionFromJSONTyped(json, false);
}

export function ColumnDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnDefinition {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfColumnTypeSpec(json)) {
        return ColumnTypeSpecFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function ColumnDefinitionToJSON(json: any): any {
    return ColumnDefinitionToJSONTyped(json, false);
}

export function ColumnDefinitionToJSONTyped(value?: ColumnDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfColumnTypeSpec(value)) {
        return ColumnTypeSpecToJSON(value as ColumnTypeSpec);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

