/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionTypeDetail
 */
export interface ConnectionTypeDetail {
    /**
     * 
     * @type {any}
     * @memberof ConnectionTypeDetail
     */
    auth?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ConnectionTypeDetail
     */
    configSchema?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectionTypeDetail
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionTypeDetail
     */
    name: string;
}

/**
 * Check if a given object implements the ConnectionTypeDetail interface.
 */
export function instanceOfConnectionTypeDetail(value: object): value is ConnectionTypeDetail {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ConnectionTypeDetailFromJSON(json: any): ConnectionTypeDetail {
    return ConnectionTypeDetailFromJSONTyped(json, false);
}

export function ConnectionTypeDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionTypeDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'auth': json['auth'] == null ? undefined : json['auth'],
        'configSchema': json['config_schema'] == null ? undefined : json['config_schema'],
        'label': json['label'],
        'name': json['name'],
    };
}

export function ConnectionTypeDetailToJSON(json: any): ConnectionTypeDetail {
    return ConnectionTypeDetailToJSONTyped(json, false);
}

export function ConnectionTypeDetailToJSONTyped(value?: ConnectionTypeDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth': value['auth'],
        'config_schema': value['configSchema'],
        'label': value['label'],
        'name': value['name'],
    };
}

