/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableRefreshError } from './TableRefreshError';
import {
    TableRefreshErrorFromJSON,
    TableRefreshErrorFromJSONTyped,
    TableRefreshErrorToJSON,
    TableRefreshErrorToJSONTyped,
} from './TableRefreshError';
import type { RefreshWarning } from './RefreshWarning';
import {
    RefreshWarningFromJSON,
    RefreshWarningFromJSONTyped,
    RefreshWarningToJSON,
    RefreshWarningToJSONTyped,
} from './RefreshWarning';

/**
 * Response for connection-wide data refresh
 * @export
 * @interface ConnectionRefreshResult
 */
export interface ConnectionRefreshResult {
    /**
     * 
     * @type {string}
     * @memberof ConnectionRefreshResult
     */
    connectionId: string;
    /**
     * 
     * @type {number}
     * @memberof ConnectionRefreshResult
     */
    durationMs: number;
    /**
     * 
     * @type {Array<TableRefreshError>}
     * @memberof ConnectionRefreshResult
     */
    errors: Array<TableRefreshError>;
    /**
     * 
     * @type {number}
     * @memberof ConnectionRefreshResult
     */
    tablesFailed: number;
    /**
     * 
     * @type {number}
     * @memberof ConnectionRefreshResult
     */
    tablesRefreshed: number;
    /**
     * 
     * @type {number}
     * @memberof ConnectionRefreshResult
     */
    totalRows: number;
    /**
     * 
     * @type {Array<RefreshWarning>}
     * @memberof ConnectionRefreshResult
     */
    warnings?: Array<RefreshWarning>;
}

/**
 * Check if a given object implements the ConnectionRefreshResult interface.
 */
export function instanceOfConnectionRefreshResult(value: object): value is ConnectionRefreshResult {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('durationMs' in value) || value['durationMs'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('tablesFailed' in value) || value['tablesFailed'] === undefined) return false;
    if (!('tablesRefreshed' in value) || value['tablesRefreshed'] === undefined) return false;
    if (!('totalRows' in value) || value['totalRows'] === undefined) return false;
    return true;
}

export function ConnectionRefreshResultFromJSON(json: any): ConnectionRefreshResult {
    return ConnectionRefreshResultFromJSONTyped(json, false);
}

export function ConnectionRefreshResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionRefreshResult {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connection_id'],
        'durationMs': json['duration_ms'],
        'errors': ((json['errors'] as Array<any>).map(TableRefreshErrorFromJSON)),
        'tablesFailed': json['tables_failed'],
        'tablesRefreshed': json['tables_refreshed'],
        'totalRows': json['total_rows'],
        'warnings': json['warnings'] == null ? undefined : ((json['warnings'] as Array<any>).map(RefreshWarningFromJSON)),
    };
}

export function ConnectionRefreshResultToJSON(json: any): ConnectionRefreshResult {
    return ConnectionRefreshResultToJSONTyped(json, false);
}

export function ConnectionRefreshResultToJSONTyped(value?: ConnectionRefreshResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_id': value['connectionId'],
        'duration_ms': value['durationMs'],
        'errors': ((value['errors'] as Array<any>).map(TableRefreshErrorToJSON)),
        'tables_failed': value['tablesFailed'],
        'tables_refreshed': value['tablesRefreshed'],
        'total_rows': value['totalRows'],
        'warnings': value['warnings'] == null ? undefined : ((value['warnings'] as Array<any>).map(RefreshWarningToJSON)),
    };
}

