/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for GET /connections/{connection_id}/health
 * @export
 * @interface ConnectionHealthResponse
 */
export interface ConnectionHealthResponse {
    /**
     * 
     * @type {string}
     * @memberof ConnectionHealthResponse
     */
    connectionId: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionHealthResponse
     */
    error?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ConnectionHealthResponse
     */
    healthy: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConnectionHealthResponse
     */
    latencyMs: number;
}

/**
 * Check if a given object implements the ConnectionHealthResponse interface.
 */
export function instanceOfConnectionHealthResponse(value: object): value is ConnectionHealthResponse {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('healthy' in value) || value['healthy'] === undefined) return false;
    if (!('latencyMs' in value) || value['latencyMs'] === undefined) return false;
    return true;
}

export function ConnectionHealthResponseFromJSON(json: any): ConnectionHealthResponse {
    return ConnectionHealthResponseFromJSONTyped(json, false);
}

export function ConnectionHealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionHealthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connection_id'],
        'error': json['error'] == null ? undefined : json['error'],
        'healthy': json['healthy'],
        'latencyMs': json['latency_ms'],
    };
}

export function ConnectionHealthResponseToJSON(json: any): ConnectionHealthResponse {
    return ConnectionHealthResponseToJSONTyped(json, false);
}

export function ConnectionHealthResponseToJSONTyped(value?: ConnectionHealthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_id': value['connectionId'],
        'error': value['error'],
        'healthy': value['healthy'],
        'latency_ms': value['latencyMs'],
    };
}

