/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error details for a failed connection schema refresh
 * @export
 * @interface ConnectionSchemaError
 */
export interface ConnectionSchemaError {
    /**
     * 
     * @type {string}
     * @memberof ConnectionSchemaError
     */
    connectionId: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionSchemaError
     */
    error: string;
}

/**
 * Check if a given object implements the ConnectionSchemaError interface.
 */
export function instanceOfConnectionSchemaError(value: object): value is ConnectionSchemaError {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ConnectionSchemaErrorFromJSON(json: any): ConnectionSchemaError {
    return ConnectionSchemaErrorFromJSONTyped(json, false);
}

export function ConnectionSchemaErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionSchemaError {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connection_id'],
        'error': json['error'],
    };
}

export function ConnectionSchemaErrorToJSON(json: any): ConnectionSchemaError {
    return ConnectionSchemaErrorToJSONTyped(json, false);
}

export function ConnectionSchemaErrorToJSONTyped(value?: ConnectionSchemaError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_id': value['connectionId'],
        'error': value['error'],
    };
}

