/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionTypeSummary
 */
export interface ConnectionTypeSummary {
    /**
     * 
     * @type {string}
     * @memberof ConnectionTypeSummary
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionTypeSummary
     */
    name: string;
}

/**
 * Check if a given object implements the ConnectionTypeSummary interface.
 */
export function instanceOfConnectionTypeSummary(value: object): value is ConnectionTypeSummary {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ConnectionTypeSummaryFromJSON(json: any): ConnectionTypeSummary {
    return ConnectionTypeSummaryFromJSONTyped(json, false);
}

export function ConnectionTypeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionTypeSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'name': json['name'],
    };
}

export function ConnectionTypeSummaryToJSON(json: any): ConnectionTypeSummary {
    return ConnectionTypeSummaryToJSONTyped(json, false);
}

export function ConnectionTypeSummaryToJSONTyped(value?: ConnectionTypeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'name': value['name'],
    };
}

