/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single connection metadata for API responses
 * @export
 * @interface ConnectionInfo
 */
export interface ConnectionInfo {
    /**
     * 
     * @type {string}
     * @memberof ConnectionInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionInfo
     */
    sourceType: string;
}

/**
 * Check if a given object implements the ConnectionInfo interface.
 */
export function instanceOfConnectionInfo(value: object): value is ConnectionInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    return true;
}

export function ConnectionInfoFromJSON(json: any): ConnectionInfo {
    return ConnectionInfoFromJSONTyped(json, false);
}

export function ConnectionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sourceType': json['source_type'],
    };
}

export function ConnectionInfoToJSON(json: any): ConnectionInfo {
    return ConnectionInfoToJSONTyped(json, false);
}

export function ConnectionInfoToJSONTyped(value?: ConnectionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'source_type': value['sourceType'],
    };
}

