/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST .../indexes
 * @export
 * @interface CreateIndexRequest
 */
export interface CreateIndexRequest {
    /**
     * When true, create the index as a background job and return a job ID for polling.
     * @type {boolean}
     * @memberof CreateIndexRequest
     */
    async?: boolean;
    /**
     * Columns to index. Required for all index types.
     * @type {Array<string>}
     * @memberof CreateIndexRequest
     */
    columns: Array<string>;
    /**
     * User-facing description of the embedding (e.g., "product descriptions").
     * @type {string}
     * @memberof CreateIndexRequest
     */
    description?: string | null;
    /**
     * Output vector dimensions. Some models support multiple dimension sizes
     * (e.g., OpenAI text-embedding-3-small supports 512 or 1536). If omitted,
     * the model's default dimensions are used.
     * @type {number}
     * @memberof CreateIndexRequest
     */
    dimensions?: number | null;
    /**
     * Embedding provider ID. When set for a vector index, the source column is treated
     * as text and embeddings are generated automatically. The vector index is then built
     * on the generated embedding column (`{column}_embedding` by default).
     * @type {string}
     * @memberof CreateIndexRequest
     */
    embeddingProviderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateIndexRequest
     */
    indexName: string;
    /**
     * Index type: "sorted" (default), "bm25" (full text search), or "vector"
     * @type {string}
     * @memberof CreateIndexRequest
     */
    indexType?: string;
    /**
     * Distance metric for vector indexes: "l2", "cosine", or "dot".
     * When omitted, defaults to "l2" for float array columns or the provider's
     * preferred metric for text columns with auto-embedding.
     * @type {string}
     * @memberof CreateIndexRequest
     */
    metric?: string | null;
    /**
     * Custom name for the generated embedding column. Defaults to `{column}_embedding`.
     * @type {string}
     * @memberof CreateIndexRequest
     */
    outputColumn?: string | null;
}

/**
 * Check if a given object implements the CreateIndexRequest interface.
 */
export function instanceOfCreateIndexRequest(value: object): value is CreateIndexRequest {
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    return true;
}

export function CreateIndexRequestFromJSON(json: any): CreateIndexRequest {
    return CreateIndexRequestFromJSONTyped(json, false);
}

export function CreateIndexRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIndexRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'async': json['async'] == null ? undefined : json['async'],
        'columns': json['columns'],
        'description': json['description'] == null ? undefined : json['description'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'embeddingProviderId': json['embedding_provider_id'] == null ? undefined : json['embedding_provider_id'],
        'indexName': json['index_name'],
        'indexType': json['index_type'] == null ? undefined : json['index_type'],
        'metric': json['metric'] == null ? undefined : json['metric'],
        'outputColumn': json['output_column'] == null ? undefined : json['output_column'],
    };
}

export function CreateIndexRequestToJSON(json: any): CreateIndexRequest {
    return CreateIndexRequestToJSONTyped(json, false);
}

export function CreateIndexRequestToJSONTyped(value?: CreateIndexRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'async': value['async'],
        'columns': value['columns'],
        'description': value['description'],
        'dimensions': value['dimensions'],
        'embedding_provider_id': value['embeddingProviderId'],
        'index_name': value['indexName'],
        'index_type': value['indexType'],
        'metric': value['metric'],
        'output_column': value['outputColumn'],
    };
}

