/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /v1/datasets
 * @export
 * @interface CreateDatasetResponse
 */
export interface CreateDatasetResponse {
    /**
     * 
     * @type {Date}
     * @memberof CreateDatasetResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateDatasetResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDatasetResponse
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDatasetResponse
     */
    schemaName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDatasetResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDatasetResponse
     */
    tableName: string;
}

/**
 * Check if a given object implements the CreateDatasetResponse interface.
 */
export function instanceOfCreateDatasetResponse(value: object): value is CreateDatasetResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('schemaName' in value) || value['schemaName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    return true;
}

export function CreateDatasetResponseFromJSON(json: any): CreateDatasetResponse {
    return CreateDatasetResponseFromJSONTyped(json, false);
}

export function CreateDatasetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatasetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'label': json['label'],
        'schemaName': json['schema_name'],
        'status': json['status'],
        'tableName': json['table_name'],
    };
}

export function CreateDatasetResponseToJSON(json: any): CreateDatasetResponse {
    return CreateDatasetResponseToJSONTyped(json, false);
}

export function CreateDatasetResponseToJSONTyped(value?: CreateDatasetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'label': value['label'],
        'schema_name': value['schemaName'],
        'status': value['status'],
        'table_name': value['tableName'],
    };
}

