/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasetSource } from './DatasetSource';
import {
    DatasetSourceFromJSON,
    DatasetSourceFromJSONTyped,
    DatasetSourceToJSON,
    DatasetSourceToJSONTyped,
} from './DatasetSource';

/**
 * Request body for POST /v1/datasets
 * @export
 * @interface CreateDatasetRequest
 */
export interface CreateDatasetRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDatasetRequest
     */
    label: string;
    /**
     * 
     * @type {DatasetSource}
     * @memberof CreateDatasetRequest
     */
    source: DatasetSource;
    /**
     * Optional table_name - if not provided, derived from label
     * @type {string}
     * @memberof CreateDatasetRequest
     */
    tableName?: string | null;
}

/**
 * Check if a given object implements the CreateDatasetRequest interface.
 */
export function instanceOfCreateDatasetRequest(value: object): value is CreateDatasetRequest {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function CreateDatasetRequestFromJSON(json: any): CreateDatasetRequest {
    return CreateDatasetRequestFromJSONTyped(json, false);
}

export function CreateDatasetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatasetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'source': DatasetSourceFromJSON(json['source']),
        'tableName': json['table_name'] == null ? undefined : json['table_name'],
    };
}

export function CreateDatasetRequestToJSON(json: any): CreateDatasetRequest {
    return CreateDatasetRequestToJSONTyped(json, false);
}

export function CreateDatasetRequestToJSONTyped(value?: CreateDatasetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'source': DatasetSourceToJSON(value['source']),
        'table_name': value['tableName'],
    };
}

