/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /embedding-providers
 * @export
 * @interface CreateEmbeddingProviderRequest
 */
export interface CreateEmbeddingProviderRequest {
    /**
     * Inline API key. If provided, a secret is auto-created and referenced.
     * Cannot be used together with `secret_name`.
     * @type {string}
     * @memberof CreateEmbeddingProviderRequest
     */
    apiKey?: string | null;
    /**
     * 
     * @type {any}
     * @memberof CreateEmbeddingProviderRequest
     */
    config?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEmbeddingProviderRequest
     */
    name: string;
    /**
     * Provider type: "local" or "service"
     * @type {string}
     * @memberof CreateEmbeddingProviderRequest
     */
    providerType: string;
    /**
     * Reference an existing secret by name (for service providers).
     * @type {string}
     * @memberof CreateEmbeddingProviderRequest
     */
    secretName?: string | null;
}

/**
 * Check if a given object implements the CreateEmbeddingProviderRequest interface.
 */
export function instanceOfCreateEmbeddingProviderRequest(value: object): value is CreateEmbeddingProviderRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('providerType' in value) || value['providerType'] === undefined) return false;
    return true;
}

export function CreateEmbeddingProviderRequestFromJSON(json: any): CreateEmbeddingProviderRequest {
    return CreateEmbeddingProviderRequestFromJSONTyped(json, false);
}

export function CreateEmbeddingProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmbeddingProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'config': json['config'] == null ? undefined : json['config'],
        'name': json['name'],
        'providerType': json['provider_type'],
        'secretName': json['secret_name'] == null ? undefined : json['secret_name'],
    };
}

export function CreateEmbeddingProviderRequestToJSON(json: any): CreateEmbeddingProviderRequest {
    return CreateEmbeddingProviderRequestToJSONTyped(json, false);
}

export function CreateEmbeddingProviderRequestToJSONTyped(value?: CreateEmbeddingProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
        'config': value['config'],
        'name': value['name'],
        'provider_type': value['providerType'],
        'secret_name': value['secretName'],
    };
}

