/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /secrets
 * @export
 * @interface CreateSecretRequest
 */
export interface CreateSecretRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSecretRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSecretRequest
     */
    value: string;
}

/**
 * Check if a given object implements the CreateSecretRequest interface.
 */
export function instanceOfCreateSecretRequest(value: object): value is CreateSecretRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CreateSecretRequestFromJSON(json: any): CreateSecretRequest {
    return CreateSecretRequestFromJSONTyped(json, false);
}

export function CreateSecretRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSecretRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function CreateSecretRequestToJSON(json: any): CreateSecretRequest {
    return CreateSecretRequestToJSONTyped(json, false);
}

export function CreateSecretRequestToJSONTyped(value?: CreateSecretRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

