/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscoveryStatus } from './DiscoveryStatus';
import {
    DiscoveryStatusFromJSON,
    DiscoveryStatusFromJSONTyped,
    DiscoveryStatusToJSON,
    DiscoveryStatusToJSONTyped,
} from './DiscoveryStatus';

/**
 * Response body for POST /connections
 * @export
 * @interface CreateConnectionResponse
 */
export interface CreateConnectionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateConnectionResponse
     */
    discoveryError?: string | null;
    /**
     * 
     * @type {DiscoveryStatus}
     * @memberof CreateConnectionResponse
     */
    discoveryStatus: DiscoveryStatus;
    /**
     * 
     * @type {string}
     * @memberof CreateConnectionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateConnectionResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateConnectionResponse
     */
    sourceType: string;
    /**
     * 
     * @type {number}
     * @memberof CreateConnectionResponse
     */
    tablesDiscovered: number;
}



/**
 * Check if a given object implements the CreateConnectionResponse interface.
 */
export function instanceOfCreateConnectionResponse(value: object): value is CreateConnectionResponse {
    if (!('discoveryStatus' in value) || value['discoveryStatus'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('tablesDiscovered' in value) || value['tablesDiscovered'] === undefined) return false;
    return true;
}

export function CreateConnectionResponseFromJSON(json: any): CreateConnectionResponse {
    return CreateConnectionResponseFromJSONTyped(json, false);
}

export function CreateConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'discoveryError': json['discovery_error'] == null ? undefined : json['discovery_error'],
        'discoveryStatus': DiscoveryStatusFromJSON(json['discovery_status']),
        'id': json['id'],
        'name': json['name'],
        'sourceType': json['source_type'],
        'tablesDiscovered': json['tables_discovered'],
    };
}

export function CreateConnectionResponseToJSON(json: any): CreateConnectionResponse {
    return CreateConnectionResponseToJSONTyped(json, false);
}

export function CreateConnectionResponseToJSONTyped(value?: CreateConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'discovery_error': value['discoveryError'],
        'discovery_status': DiscoveryStatusToJSON(value['discoveryStatus']),
        'id': value['id'],
        'name': value['name'],
        'source_type': value['sourceType'],
        'tables_discovered': value['tablesDiscovered'],
    };
}

