/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSandboxRequest
 */
export interface CreateSandboxRequest {
    /**
     * Human-readable name for the sandbox.
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    name?: string;
    /**
     * Optional markdown notes.
     * @type {string}
     * @memberof CreateSandboxRequest
     */
    markdown?: string;
}

/**
 * Check if a given object implements the CreateSandboxRequest interface.
 */
export function instanceOfCreateSandboxRequest(value: object): value is CreateSandboxRequest {
    return true;
}

export function CreateSandboxRequestFromJSON(json: any): CreateSandboxRequest {
    return CreateSandboxRequestFromJSONTyped(json, false);
}

export function CreateSandboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSandboxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'markdown': json['markdown'] == null ? undefined : json['markdown'],
    };
}

export function CreateSandboxRequestToJSON(json: any): CreateSandboxRequest {
    return CreateSandboxRequestToJSONTyped(json, false);
}

export function CreateSandboxRequestToJSONTyped(value?: CreateSandboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'markdown': value['markdown'],
    };
}

