/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /v1/queries
 * @export
 * @interface CreateSavedQueryRequest
 */
export interface CreateSavedQueryRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSavedQueryRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedQueryRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedQueryRequest
     */
    sql: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSavedQueryRequest
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the CreateSavedQueryRequest interface.
 */
export function instanceOfCreateSavedQueryRequest(value: object): value is CreateSavedQueryRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sql' in value) || value['sql'] === undefined) return false;
    return true;
}

export function CreateSavedQueryRequestFromJSON(json: any): CreateSavedQueryRequest {
    return CreateSavedQueryRequestFromJSONTyped(json, false);
}

export function CreateSavedQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSavedQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'sql': json['sql'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function CreateSavedQueryRequestToJSON(json: any): CreateSavedQueryRequest {
    return CreateSavedQueryRequestToJSONTyped(json, false);
}

export function CreateSavedQueryRequestToJSONTyped(value?: CreateSavedQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'sql': value['sql'],
        'tags': value['tags'],
    };
}

