/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InlineDatasetSource } from './InlineDatasetSource';
import {
    instanceOfInlineDatasetSource,
    InlineDatasetSourceFromJSON,
    InlineDatasetSourceFromJSONTyped,
    InlineDatasetSourceToJSON,
} from './InlineDatasetSource';
import type { SavedQueryDatasetSource } from './SavedQueryDatasetSource';
import {
    instanceOfSavedQueryDatasetSource,
    SavedQueryDatasetSourceFromJSON,
    SavedQueryDatasetSourceFromJSONTyped,
    SavedQueryDatasetSourceToJSON,
} from './SavedQueryDatasetSource';
import type { SqlQueryDatasetSource } from './SqlQueryDatasetSource';
import {
    instanceOfSqlQueryDatasetSource,
    SqlQueryDatasetSourceFromJSON,
    SqlQueryDatasetSourceFromJSONTyped,
    SqlQueryDatasetSourceToJSON,
} from './SqlQueryDatasetSource';
import type { UploadDatasetSource } from './UploadDatasetSource';
import {
    instanceOfUploadDatasetSource,
    UploadDatasetSourceFromJSON,
    UploadDatasetSourceFromJSONTyped,
    UploadDatasetSourceToJSON,
} from './UploadDatasetSource';
import type { UrlDatasetSource } from './UrlDatasetSource';
import {
    instanceOfUrlDatasetSource,
    UrlDatasetSourceFromJSON,
    UrlDatasetSourceFromJSONTyped,
    UrlDatasetSourceToJSON,
} from './UrlDatasetSource';

/**
 * @type DatasetSource
 * Dataset source specification
 * @export
 */
export type DatasetSource = InlineDatasetSource | SavedQueryDatasetSource | SqlQueryDatasetSource | UploadDatasetSource | UrlDatasetSource;

export function DatasetSourceFromJSON(json: any): DatasetSource {
    return DatasetSourceFromJSONTyped(json, false);
}

export function DatasetSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetSource {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfInlineDatasetSource(json)) {
        return InlineDatasetSourceFromJSONTyped(json, true);
    }
    if (instanceOfSavedQueryDatasetSource(json)) {
        return SavedQueryDatasetSourceFromJSONTyped(json, true);
    }
    if (instanceOfSqlQueryDatasetSource(json)) {
        return SqlQueryDatasetSourceFromJSONTyped(json, true);
    }
    if (instanceOfUploadDatasetSource(json)) {
        return UploadDatasetSourceFromJSONTyped(json, true);
    }
    if (instanceOfUrlDatasetSource(json)) {
        return UrlDatasetSourceFromJSONTyped(json, true);
    }
    return {} as any;
}

export function DatasetSourceToJSON(json: any): any {
    return DatasetSourceToJSONTyped(json, false);
}

export function DatasetSourceToJSONTyped(value?: DatasetSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfInlineDatasetSource(value)) {
        return InlineDatasetSourceToJSON(value as InlineDatasetSource);
    }
    if (instanceOfSavedQueryDatasetSource(value)) {
        return SavedQueryDatasetSourceToJSON(value as SavedQueryDatasetSource);
    }
    if (instanceOfSqlQueryDatasetSource(value)) {
        return SqlQueryDatasetSourceToJSON(value as SqlQueryDatasetSource);
    }
    if (instanceOfUploadDatasetSource(value)) {
        return UploadDatasetSourceToJSON(value as UploadDatasetSource);
    }
    if (instanceOfUrlDatasetSource(value)) {
        return UrlDatasetSourceToJSON(value as UrlDatasetSource);
    }
    return {};
}

