/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Dataset version summary
 * @export
 * @interface DatasetVersionSummary
 */
export interface DatasetVersionSummary {
    /**
     * 
     * @type {Date}
     * @memberof DatasetVersionSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DatasetVersionSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetVersionSummary
     */
    sourceType: string;
    /**
     * 
     * @type {number}
     * @memberof DatasetVersionSummary
     */
    version: number;
}

/**
 * Check if a given object implements the DatasetVersionSummary interface.
 */
export function instanceOfDatasetVersionSummary(value: object): value is DatasetVersionSummary {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function DatasetVersionSummaryFromJSON(json: any): DatasetVersionSummary {
    return DatasetVersionSummaryFromJSONTyped(json, false);
}

export function DatasetVersionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetVersionSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'sourceType': json['source_type'],
        'version': json['version'],
    };
}

export function DatasetVersionSummaryToJSON(json: any): DatasetVersionSummary {
    return DatasetVersionSummaryToJSONTyped(json, false);
}

export function DatasetVersionSummaryToJSONTyped(value?: DatasetVersionSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'source_type': value['sourceType'],
        'version': value['version'],
    };
}

