/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Dataset summary for listing
 * @export
 * @interface DatasetSummary
 */
export interface DatasetSummary {
    /**
     * 
     * @type {Date}
     * @memberof DatasetSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DatasetSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetSummary
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof DatasetSummary
     */
    latestVersion: number;
    /**
     * 
     * @type {number}
     * @memberof DatasetSummary
     */
    pinnedVersion?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DatasetSummary
     */
    schemaName: string;
    /**
     * 
     * @type {string}
     * @memberof DatasetSummary
     */
    tableName: string;
    /**
     * 
     * @type {Date}
     * @memberof DatasetSummary
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the DatasetSummary interface.
 */
export function instanceOfDatasetSummary(value: object): value is DatasetSummary {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('latestVersion' in value) || value['latestVersion'] === undefined) return false;
    if (!('schemaName' in value) || value['schemaName'] === undefined) return false;
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function DatasetSummaryFromJSON(json: any): DatasetSummary {
    return DatasetSummaryFromJSONTyped(json, false);
}

export function DatasetSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'label': json['label'],
        'latestVersion': json['latest_version'],
        'pinnedVersion': json['pinned_version'] == null ? undefined : json['pinned_version'],
        'schemaName': json['schema_name'],
        'tableName': json['table_name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function DatasetSummaryToJSON(json: any): DatasetSummary {
    return DatasetSummaryToJSONTyped(json, false);
}

export function DatasetSummaryToJSONTyped(value?: DatasetSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'label': value['label'],
        'latest_version': value['latestVersion'],
        'pinned_version': value['pinnedVersion'],
        'schema_name': value['schemaName'],
        'table_name': value['tableName'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

