/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColumnDefinition } from './ColumnDefinition';
import {
    ColumnDefinitionFromJSON,
    ColumnDefinitionFromJSONTyped,
    ColumnDefinitionToJSON,
    ColumnDefinitionToJSONTyped,
} from './ColumnDefinition';

/**
 * Create from a previously uploaded file
 * @export
 * @interface DatasetSourceOneOf
 */
export interface DatasetSourceOneOf {
    /**
     * Optional explicit column definitions. Keys are column names, values are type specs.
     * When provided, the schema is built from these definitions instead of being inferred.
     * @type {{ [key: string]: ColumnDefinition; }}
     * @memberof DatasetSourceOneOf
     */
    columns?: { [key: string]: ColumnDefinition; };
    /**
     * 
     * @type {string}
     * @memberof DatasetSourceOneOf
     */
    format?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DatasetSourceOneOf
     */
    uploadId: string;
}

/**
 * Check if a given object implements the DatasetSourceOneOf interface.
 */
export function instanceOfDatasetSourceOneOf(value: object): value is DatasetSourceOneOf {
    if (!('uploadId' in value) || value['uploadId'] === undefined) return false;
    return true;
}

export function DatasetSourceOneOfFromJSON(json: any): DatasetSourceOneOf {
    return DatasetSourceOneOfFromJSONTyped(json, false);
}

export function DatasetSourceOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetSourceOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : (mapValues(json['columns'], ColumnDefinitionFromJSON)),
        'format': json['format'] == null ? undefined : json['format'],
        'uploadId': json['upload_id'],
    };
}

export function DatasetSourceOneOfToJSON(json: any): DatasetSourceOneOf {
    return DatasetSourceOneOfToJSONTyped(json, false);
}

export function DatasetSourceOneOfToJSONTyped(value?: DatasetSourceOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'] == null ? undefined : (mapValues(value['columns'], ColumnDefinitionToJSON)),
        'format': value['format'],
        'upload_id': value['uploadId'],
    };
}

