/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteSandboxResponse
 */
export interface DeleteSandboxResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteSandboxResponse
     */
    ok: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteSandboxResponse
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the DeleteSandboxResponse interface.
 */
export function instanceOfDeleteSandboxResponse(value: object): value is DeleteSandboxResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function DeleteSandboxResponseFromJSON(json: any): DeleteSandboxResponse {
    return DeleteSandboxResponseFromJSONTyped(json, false);
}

export function DeleteSandboxResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSandboxResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'deleted': json['deleted'],
    };
}

export function DeleteSandboxResponseToJSON(json: any): DeleteSandboxResponse {
    return DeleteSandboxResponseToJSONTyped(json, false);
}

export function DeleteSandboxResponseToJSONTyped(value?: DeleteSandboxResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'deleted': value['deleted'],
    };
}

