/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Discovery status for connection creation
 * @export
 */
export const DiscoveryStatus = {
    Success: 'success',
    Skipped: 'skipped',
    Failed: 'failed'
} as const;
export type DiscoveryStatus = typeof DiscoveryStatus[keyof typeof DiscoveryStatus];


export function instanceOfDiscoveryStatus(value: any): boolean {
    for (const key in DiscoveryStatus) {
        if (Object.prototype.hasOwnProperty.call(DiscoveryStatus, key)) {
            if (DiscoveryStatus[key as keyof typeof DiscoveryStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DiscoveryStatusFromJSON(json: any): DiscoveryStatus {
    return DiscoveryStatusFromJSONTyped(json, false);
}

export function DiscoveryStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryStatus {
    return json as DiscoveryStatus;
}

export function DiscoveryStatusToJSON(value?: DiscoveryStatus | null): any {
    return value as any;
}

export function DiscoveryStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DiscoveryStatus {
    return value as DiscoveryStatus;
}

