/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /v1/queries/{id}/execute
 * @export
 * @interface ExecuteSavedQueryRequest
 */
export interface ExecuteSavedQueryRequest {
    /**
     * 
     * @type {number}
     * @memberof ExecuteSavedQueryRequest
     */
    version?: number | null;
}

/**
 * Check if a given object implements the ExecuteSavedQueryRequest interface.
 */
export function instanceOfExecuteSavedQueryRequest(value: object): value is ExecuteSavedQueryRequest {
    return true;
}

export function ExecuteSavedQueryRequestFromJSON(json: any): ExecuteSavedQueryRequest {
    return ExecuteSavedQueryRequestFromJSONTyped(json, false);
}

export function ExecuteSavedQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteSavedQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ExecuteSavedQueryRequestToJSON(json: any): ExecuteSavedQueryRequest {
    return ExecuteSavedQueryRequestToJSONTyped(json, false);
}

export function ExecuteSavedQueryRequestToJSONTyped(value?: ExecuteSavedQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
    };
}

