/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for GET /connections/{connection_id}
 * @export
 * @interface GetConnectionResponse
 */
export interface GetConnectionResponse {
    /**
     * 
     * @type {string}
     * @memberof GetConnectionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionResponse
     */
    sourceType: string;
    /**
     * 
     * @type {number}
     * @memberof GetConnectionResponse
     */
    syncedTableCount: number;
    /**
     * 
     * @type {number}
     * @memberof GetConnectionResponse
     */
    tableCount: number;
}

/**
 * Check if a given object implements the GetConnectionResponse interface.
 */
export function instanceOfGetConnectionResponse(value: object): value is GetConnectionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('syncedTableCount' in value) || value['syncedTableCount'] === undefined) return false;
    if (!('tableCount' in value) || value['tableCount'] === undefined) return false;
    return true;
}

export function GetConnectionResponseFromJSON(json: any): GetConnectionResponse {
    return GetConnectionResponseFromJSONTyped(json, false);
}

export function GetConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sourceType': json['source_type'],
        'syncedTableCount': json['synced_table_count'],
        'tableCount': json['table_count'],
    };
}

export function GetConnectionResponseToJSON(json: any): GetConnectionResponse {
    return GetConnectionResponseToJSONTyped(json, false);
}

export function GetConnectionResponseToJSONTyped(value?: GetConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'source_type': value['sourceType'],
        'synced_table_count': value['syncedTableCount'],
        'table_count': value['tableCount'],
    };
}

