/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColumnInfo } from './ColumnInfo';
import {
    ColumnInfoFromJSON,
    ColumnInfoFromJSONTyped,
    ColumnInfoToJSON,
    ColumnInfoToJSONTyped,
} from './ColumnInfo';

/**
 * Response body for GET /v1/datasets/{id}
 * @export
 * @interface GetDatasetResponse
 */
export interface GetDatasetResponse {
    /**
     * 
     * @type {Array<ColumnInfo>}
     * @memberof GetDatasetResponse
     */
    columns: Array<ColumnInfo>;
    /**
     * 
     * @type {Date}
     * @memberof GetDatasetResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetDatasetResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetDatasetResponse
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof GetDatasetResponse
     */
    schemaName: string;
    /**
     * 
     * @type {string}
     * @memberof GetDatasetResponse
     */
    sourceType: string;
    /**
     * 
     * @type {string}
     * @memberof GetDatasetResponse
     */
    tableName: string;
    /**
     * 
     * @type {Date}
     * @memberof GetDatasetResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the GetDatasetResponse interface.
 */
export function instanceOfGetDatasetResponse(value: object): value is GetDatasetResponse {
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('schemaName' in value) || value['schemaName'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetDatasetResponseFromJSON(json: any): GetDatasetResponse {
    return GetDatasetResponseFromJSONTyped(json, false);
}

export function GetDatasetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDatasetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': ((json['columns'] as Array<any>).map(ColumnInfoFromJSON)),
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'label': json['label'],
        'schemaName': json['schema_name'],
        'sourceType': json['source_type'],
        'tableName': json['table_name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function GetDatasetResponseToJSON(json: any): GetDatasetResponse {
    return GetDatasetResponseToJSONTyped(json, false);
}

export function GetDatasetResponseToJSONTyped(value?: GetDatasetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': ((value['columns'] as Array<any>).map(ColumnInfoToJSON)),
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'label': value['label'],
        'schema_name': value['schemaName'],
        'source_type': value['sourceType'],
        'table_name': value['tableName'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

