/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for GET /results/{id}
 * Returns status and optionally the result data
 * @export
 * @interface GetResultResponse
 */
export interface GetResultResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetResultResponse
     */
    columns?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof GetResultResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {Array<boolean>}
     * @memberof GetResultResponse
     */
    nullable?: Array<boolean> | null;
    /**
     * 
     * @type {string}
     * @memberof GetResultResponse
     */
    resultId: string;
    /**
     * 
     * @type {number}
     * @memberof GetResultResponse
     */
    rowCount?: number | null;
    /**
     * Array of rows, where each row is an array of column values.
     * @type {Array<Array<string>>}
     * @memberof GetResultResponse
     */
    rows?: Array<Array<string>> | null;
    /**
     * 
     * @type {string}
     * @memberof GetResultResponse
     */
    status: string;
}

/**
 * Check if a given object implements the GetResultResponse interface.
 */
export function instanceOfGetResultResponse(value: object): value is GetResultResponse {
    if (!('resultId' in value) || value['resultId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetResultResponseFromJSON(json: any): GetResultResponse {
    return GetResultResponseFromJSONTyped(json, false);
}

export function GetResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : json['columns'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'nullable': json['nullable'] == null ? undefined : json['nullable'],
        'resultId': json['result_id'],
        'rowCount': json['row_count'] == null ? undefined : json['row_count'],
        'rows': json['rows'] == null ? undefined : json['rows'],
        'status': json['status'],
    };
}

export function GetResultResponseToJSON(json: any): GetResultResponse {
    return GetResultResponseToJSONTyped(json, false);
}

export function GetResultResponseToJSONTyped(value?: GetResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'],
        'error_message': value['errorMessage'],
        'nullable': value['nullable'],
        'result_id': value['resultId'],
        'row_count': value['rowCount'],
        'rows': value['rows'],
        'status': value['status'],
    };
}

