/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for GET /secrets/{name}
 * @export
 * @interface GetSecretResponse
 */
export interface GetSecretResponse {
    /**
     * 
     * @type {Date}
     * @memberof GetSecretResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetSecretResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof GetSecretResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the GetSecretResponse interface.
 */
export function instanceOfGetSecretResponse(value: object): value is GetSecretResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetSecretResponseFromJSON(json: any): GetSecretResponse {
    return GetSecretResponseFromJSONTyped(json, false);
}

export function GetSecretResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSecretResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function GetSecretResponseToJSON(json: any): GetSecretResponse {
    return GetSecretResponseToJSONTyped(json, false);
}

export function GetSecretResponseToJSONTyped(value?: GetSecretResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'name': value['name'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

