/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IndexStatus } from './IndexStatus';
import {
    IndexStatusFromJSON,
    IndexStatusFromJSONTyped,
    IndexStatusToJSON,
    IndexStatusToJSONTyped,
} from './IndexStatus';

/**
 * Result payload for a `create_index` job, and response for index endpoints.
 * @export
 * @interface IndexInfoResponse
 */
export interface IndexInfoResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof IndexInfoResponse
     */
    columns: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof IndexInfoResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof IndexInfoResponse
     */
    indexName: string;
    /**
     * 
     * @type {string}
     * @memberof IndexInfoResponse
     */
    indexType: string;
    /**
     * Distance metric this index was built with. Only present for vector indexes.
     * @type {string}
     * @memberof IndexInfoResponse
     */
    metric?: string | null;
    /**
     * 
     * @type {IndexStatus}
     * @memberof IndexInfoResponse
     */
    status: IndexStatus;
    /**
     * 
     * @type {Date}
     * @memberof IndexInfoResponse
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the IndexInfoResponse interface.
 */
export function instanceOfIndexInfoResponse(value: object): value is IndexInfoResponse {
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('indexName' in value) || value['indexName'] === undefined) return false;
    if (!('indexType' in value) || value['indexType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function IndexInfoResponseFromJSON(json: any): IndexInfoResponse {
    return IndexInfoResponseFromJSONTyped(json, false);
}

export function IndexInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'],
        'createdAt': (new Date(json['created_at'])),
        'indexName': json['index_name'],
        'indexType': json['index_type'],
        'metric': json['metric'] == null ? undefined : json['metric'],
        'status': IndexStatusFromJSON(json['status']),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function IndexInfoResponseToJSON(json: any): IndexInfoResponse {
    return IndexInfoResponseToJSONTyped(json, false);
}

export function IndexInfoResponseToJSONTyped(value?: IndexInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'],
        'created_at': value['createdAt'].toISOString(),
        'index_name': value['indexName'],
        'index_type': value['indexType'],
        'metric': value['metric'],
        'status': IndexStatusToJSON(value['status']),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

