/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Index build status exposed to API consumers.
 * @export
 */
export const IndexStatus = {
    Ready: 'ready',
    Pending: 'pending'
} as const;
export type IndexStatus = typeof IndexStatus[keyof typeof IndexStatus];


export function instanceOfIndexStatus(value: any): boolean {
    for (const key in IndexStatus) {
        if (Object.prototype.hasOwnProperty.call(IndexStatus, key)) {
            if (IndexStatus[key as keyof typeof IndexStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IndexStatusFromJSON(json: any): IndexStatus {
    return IndexStatusFromJSONTyped(json, false);
}

export function IndexStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexStatus {
    return json as IndexStatus;
}

export function IndexStatusToJSON(value?: IndexStatus | null): any {
    return value as any;
}

export function IndexStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): IndexStatus {
    return value as IndexStatus;
}

