/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableInfo } from './TableInfo';
import {
    TableInfoFromJSON,
    TableInfoFromJSONTyped,
    TableInfoToJSON,
    TableInfoToJSONTyped,
} from './TableInfo';

/**
 * Response body for GET /information_schema
 * @export
 * @interface InformationSchemaResponse
 */
export interface InformationSchemaResponse {
    /**
     * 
     * @type {number}
     * @memberof InformationSchemaResponse
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof InformationSchemaResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {number}
     * @memberof InformationSchemaResponse
     */
    limit: number;
    /**
     * 
     * @type {string}
     * @memberof InformationSchemaResponse
     */
    nextCursor?: string | null;
    /**
     * 
     * @type {Array<TableInfo>}
     * @memberof InformationSchemaResponse
     */
    tables: Array<TableInfo>;
}

/**
 * Check if a given object implements the InformationSchemaResponse interface.
 */
export function instanceOfInformationSchemaResponse(value: object): value is InformationSchemaResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('tables' in value) || value['tables'] === undefined) return false;
    return true;
}

export function InformationSchemaResponseFromJSON(json: any): InformationSchemaResponse {
    return InformationSchemaResponseFromJSONTyped(json, false);
}

export function InformationSchemaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InformationSchemaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'hasMore': json['has_more'],
        'limit': json['limit'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'tables': ((json['tables'] as Array<any>).map(TableInfoFromJSON)),
    };
}

export function InformationSchemaResponseToJSON(json: any): InformationSchemaResponse {
    return InformationSchemaResponseToJSONTyped(json, false);
}

export function InformationSchemaResponseToJSONTyped(value?: InformationSchemaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'has_more': value['hasMore'],
        'limit': value['limit'],
        'next_cursor': value['nextCursor'],
        'tables': ((value['tables'] as Array<any>).map(TableInfoToJSON)),
    };
}

