/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColumnDefinition } from './ColumnDefinition';
import {
    ColumnDefinitionFromJSON,
    ColumnDefinitionFromJSONTyped,
    ColumnDefinitionToJSON,
    ColumnDefinitionToJSONTyped,
} from './ColumnDefinition';

/**
 * Inline data specification
 * @export
 * @interface InlineData
 */
export interface InlineData {
    /**
     * Optional explicit column definitions. Keys are column names, values are type specs.
     * When provided, the schema is built from these definitions instead of being inferred.
     * @type {{ [key: string]: ColumnDefinition; }}
     * @memberof InlineData
     */
    columns?: { [key: string]: ColumnDefinition; };
    /**
     * 
     * @type {string}
     * @memberof InlineData
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof InlineData
     */
    format: string;
}

/**
 * Check if a given object implements the InlineData interface.
 */
export function instanceOfInlineData(value: object): value is InlineData {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    return true;
}

export function InlineDataFromJSON(json: any): InlineData {
    return InlineDataFromJSONTyped(json, false);
}

export function InlineDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineData {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : (mapValues(json['columns'], ColumnDefinitionFromJSON)),
        'content': json['content'],
        'format': json['format'],
    };
}

export function InlineDataToJSON(json: any): InlineData {
    return InlineDataToJSONTyped(json, false);
}

export function InlineDataToJSONTyped(value?: InlineData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'] == null ? undefined : (mapValues(value['columns'], ColumnDefinitionToJSON)),
        'content': value['content'],
        'format': value['format'],
    };
}

