/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InlineData } from './InlineData';
import {
    InlineDataFromJSON,
    InlineDataFromJSONTyped,
    InlineDataToJSON,
    InlineDataToJSONTyped,
} from './InlineData';

/**
 * Create dataset from inline data (small payloads)
 * @export
 * @interface InlineDatasetSource
 */
export interface InlineDatasetSource {
    /**
     * 
     * @type {InlineData}
     * @memberof InlineDatasetSource
     */
    inline: InlineData;
}

/**
 * Check if a given object implements the InlineDatasetSource interface.
 */
export function instanceOfInlineDatasetSource(value: object): value is InlineDatasetSource {
    if (!('inline' in value) || value['inline'] === undefined) return false;
    return true;
}

export function InlineDatasetSourceFromJSON(json: any): InlineDatasetSource {
    return InlineDatasetSourceFromJSONTyped(json, false);
}

export function InlineDatasetSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineDatasetSource {
    if (json == null) {
        return json;
    }
    return {
        
        'inline': InlineDataFromJSON(json['inline']),
    };
}

export function InlineDatasetSourceToJSON(json: any): InlineDatasetSource {
    return InlineDatasetSourceToJSONTyped(json, false);
}

export function InlineDatasetSourceToJSONTyped(value?: InlineDatasetSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inline': InlineDataToJSON(value['inline']),
    };
}

