/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type JobResult
 * Job-specific result payload. The shape depends on the job type.
 * Null while the job is pending or running.
 * @export
 */
export type JobResult = ConnectionRefreshResult | IndexInfoResponse | TableRefreshResult;

export function JobResultFromJSON(json: any): JobResult {
    return JobResultFromJSONTyped(json, false);
}

export function JobResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobResult {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfConnectionRefreshResult(json)) {
        return ConnectionRefreshResultFromJSONTyped(json, true);
    }
    if (instanceOfIndexInfoResponse(json)) {
        return IndexInfoResponseFromJSONTyped(json, true);
    }
    if (instanceOfTableRefreshResult(json)) {
        return TableRefreshResultFromJSONTyped(json, true);
    }
    return {} as any;
}

export function JobResultToJSON(json: any): any {
    return JobResultToJSONTyped(json, false);
}

export function JobResultToJSONTyped(value?: JobResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfConnectionRefreshResult(value)) {
        return ConnectionRefreshResultToJSON(value as ConnectionRefreshResult);
    }
    if (instanceOfIndexInfoResponse(value)) {
        return IndexInfoResponseToJSON(value as IndexInfoResponse);
    }
    if (instanceOfTableRefreshResult(value)) {
        return TableRefreshResultToJSON(value as TableRefreshResult);
    }
    return {};
}

