/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';
import type { JobType } from './JobType';
import {
    JobTypeFromJSON,
    JobTypeFromJSONTyped,
    JobTypeToJSON,
    JobTypeToJSONTyped,
} from './JobType';
import type { JobResult } from './JobResult';
import {
    JobResultFromJSON,
    JobResultFromJSONTyped,
    JobResultToJSON,
    JobResultToJSONTyped,
} from './JobResult';

/**
 * Response body for GET /v1/jobs/{id}
 * @export
 * @interface JobStatusResponse
 */
export interface JobStatusResponse {
    /**
     * Number of execution attempts (including the current one).
     * @type {number}
     * @memberof JobStatusResponse
     */
    attempts: number;
    /**
     * 
     * @type {Date}
     * @memberof JobStatusResponse
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JobStatusResponse
     */
    createdAt: Date;
    /**
     * Error or warning message. Set when status is `failed` or `partially_succeeded`.
     * @type {string}
     * @memberof JobStatusResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    id: string;
    /**
     * 
     * @type {JobType}
     * @memberof JobStatusResponse
     */
    jobType: JobType;
    /**
     * Job-specific result payload. Null while the job is pending or running.
     * @type {JobResult}
     * @memberof JobStatusResponse
     */
    result?: JobResult | null;
    /**
     * 
     * @type {JobStatus}
     * @memberof JobStatusResponse
     */
    status: JobStatus;
}



/**
 * Check if a given object implements the JobStatusResponse interface.
 */
export function instanceOfJobStatusResponse(value: object): value is JobStatusResponse {
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('jobType' in value) || value['jobType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function JobStatusResponseFromJSON(json: any): JobStatusResponse {
    return JobStatusResponseFromJSONTyped(json, false);
}

export function JobStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'attempts': json['attempts'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'id': json['id'],
        'jobType': JobTypeFromJSON(json['job_type']),
        'result': json['result'] == null ? undefined : JobResultFromJSON(json['result']),
        'status': JobStatusFromJSON(json['status']),
    };
}

export function JobStatusResponseToJSON(json: any): JobStatusResponse {
    return JobStatusResponseToJSONTyped(json, false);
}

export function JobStatusResponseToJSONTyped(value?: JobStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempts': value['attempts'],
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'error_message': value['errorMessage'],
        'id': value['id'],
        'job_type': JobTypeToJSON(value['jobType']),
        'result': JobResultToJSON(value['result']),
        'status': JobStatusToJSON(value['status']),
    };
}

