/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Current status of a background job.
 * @export
 */
export const JobStatus = {
    Pending: 'pending',
    Running: 'running',
    Succeeded: 'succeeded',
    PartiallySucceeded: 'partially_succeeded',
    Failed: 'failed'
} as const;
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];


export function instanceOfJobStatus(value: any): boolean {
    for (const key in JobStatus) {
        if (Object.prototype.hasOwnProperty.call(JobStatus, key)) {
            if (JobStatus[key as keyof typeof JobStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobStatusFromJSON(json: any): JobStatus {
    return JobStatusFromJSONTyped(json, false);
}

export function JobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatus {
    return json as JobStatus;
}

export function JobStatusToJSON(value?: JobStatus | null): any {
    return value as any;
}

export function JobStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): JobStatus {
    return value as JobStatus;
}

