/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Background job types returned by the API.
 * @export
 */
export const JobType = {
    Noop: 'noop',
    DataRefreshTable: 'data_refresh_table',
    DataRefreshConnection: 'data_refresh_connection',
    CreateIndex: 'create_index'
} as const;
export type JobType = typeof JobType[keyof typeof JobType];


export function instanceOfJobType(value: any): boolean {
    for (const key in JobType) {
        if (Object.prototype.hasOwnProperty.call(JobType, key)) {
            if (JobType[key as keyof typeof JobType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobTypeFromJSON(json: any): JobType {
    return JobTypeFromJSONTyped(json, false);
}

export function JobTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobType {
    return json as JobType;
}

export function JobTypeToJSON(value?: JobType | null): any {
    return value as any;
}

export function JobTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JobType {
    return value as JobType;
}

