/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadInfo } from './UploadInfo';
import {
    UploadInfoFromJSON,
    UploadInfoFromJSONTyped,
    UploadInfoToJSON,
    UploadInfoToJSONTyped,
} from './UploadInfo';

/**
 * Response body for GET /v1/files
 * @export
 * @interface ListUploadsResponse
 */
export interface ListUploadsResponse {
    /**
     * 
     * @type {Array<UploadInfo>}
     * @memberof ListUploadsResponse
     */
    uploads: Array<UploadInfo>;
}

/**
 * Check if a given object implements the ListUploadsResponse interface.
 */
export function instanceOfListUploadsResponse(value: object): value is ListUploadsResponse {
    if (!('uploads' in value) || value['uploads'] === undefined) return false;
    return true;
}

export function ListUploadsResponseFromJSON(json: any): ListUploadsResponse {
    return ListUploadsResponseFromJSONTyped(json, false);
}

export function ListUploadsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUploadsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uploads': ((json['uploads'] as Array<any>).map(UploadInfoFromJSON)),
    };
}

export function ListUploadsResponseToJSON(json: any): ListUploadsResponse {
    return ListUploadsResponseToJSONTyped(json, false);
}

export function ListUploadsResponseToJSONTyped(value?: ListUploadsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploads': ((value['uploads'] as Array<any>).map(UploadInfoToJSON)),
    };
}

