/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SavedQueryVersionInfo } from './SavedQueryVersionInfo';
import {
    SavedQueryVersionInfoFromJSON,
    SavedQueryVersionInfoFromJSONTyped,
    SavedQueryVersionInfoToJSON,
    SavedQueryVersionInfoToJSONTyped,
} from './SavedQueryVersionInfo';

/**
 * Response body for GET /v1/queries/{id}/versions
 * @export
 * @interface ListSavedQueryVersionsResponse
 */
export interface ListSavedQueryVersionsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListSavedQueryVersionsResponse
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListSavedQueryVersionsResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListSavedQueryVersionsResponse
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListSavedQueryVersionsResponse
     */
    offset: number;
    /**
     * 
     * @type {string}
     * @memberof ListSavedQueryVersionsResponse
     */
    savedQueryId: string;
    /**
     * 
     * @type {Array<SavedQueryVersionInfo>}
     * @memberof ListSavedQueryVersionsResponse
     */
    versions: Array<SavedQueryVersionInfo>;
}

/**
 * Check if a given object implements the ListSavedQueryVersionsResponse interface.
 */
export function instanceOfListSavedQueryVersionsResponse(value: object): value is ListSavedQueryVersionsResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('savedQueryId' in value) || value['savedQueryId'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    return true;
}

export function ListSavedQueryVersionsResponseFromJSON(json: any): ListSavedQueryVersionsResponse {
    return ListSavedQueryVersionsResponseFromJSONTyped(json, false);
}

export function ListSavedQueryVersionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSavedQueryVersionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'hasMore': json['has_more'],
        'limit': json['limit'],
        'offset': json['offset'],
        'savedQueryId': json['saved_query_id'],
        'versions': ((json['versions'] as Array<any>).map(SavedQueryVersionInfoFromJSON)),
    };
}

export function ListSavedQueryVersionsResponseToJSON(json: any): ListSavedQueryVersionsResponse {
    return ListSavedQueryVersionsResponseToJSONTyped(json, false);
}

export function ListSavedQueryVersionsResponseToJSONTyped(value?: ListSavedQueryVersionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'has_more': value['hasMore'],
        'limit': value['limit'],
        'offset': value['offset'],
        'saved_query_id': value['savedQueryId'],
        'versions': ((value['versions'] as Array<any>).map(SavedQueryVersionInfoToJSON)),
    };
}

