/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sandbox } from './Sandbox';
import {
    SandboxFromJSON,
    SandboxFromJSONTyped,
    SandboxToJSON,
    SandboxToJSONTyped,
} from './Sandbox';

/**
 * 
 * @export
 * @interface ListSandboxesResponse
 */
export interface ListSandboxesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListSandboxesResponse
     */
    ok: boolean;
    /**
     * 
     * @type {Array<Sandbox>}
     * @memberof ListSandboxesResponse
     */
    sandboxes: Array<Sandbox>;
}

/**
 * Check if a given object implements the ListSandboxesResponse interface.
 */
export function instanceOfListSandboxesResponse(value: object): value is ListSandboxesResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('sandboxes' in value) || value['sandboxes'] === undefined) return false;
    return true;
}

export function ListSandboxesResponseFromJSON(json: any): ListSandboxesResponse {
    return ListSandboxesResponseFromJSONTyped(json, false);
}

export function ListSandboxesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSandboxesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'sandboxes': ((json['sandboxes'] as Array<any>).map(SandboxFromJSON)),
    };
}

export function ListSandboxesResponseToJSON(json: any): ListSandboxesResponse {
    return ListSandboxesResponseToJSONTyped(json, false);
}

export function ListSandboxesResponseToJSONTyped(value?: ListSandboxesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'sandboxes': ((value['sandboxes'] as Array<any>).map(SandboxToJSON)),
    };
}

