/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecretMetadataResponse } from './SecretMetadataResponse';
import {
    SecretMetadataResponseFromJSON,
    SecretMetadataResponseFromJSONTyped,
    SecretMetadataResponseToJSON,
    SecretMetadataResponseToJSONTyped,
} from './SecretMetadataResponse';

/**
 * Response body for GET /secrets
 * @export
 * @interface ListSecretsResponse
 */
export interface ListSecretsResponse {
    /**
     * 
     * @type {Array<SecretMetadataResponse>}
     * @memberof ListSecretsResponse
     */
    secrets: Array<SecretMetadataResponse>;
}

/**
 * Check if a given object implements the ListSecretsResponse interface.
 */
export function instanceOfListSecretsResponse(value: object): value is ListSecretsResponse {
    if (!('secrets' in value) || value['secrets'] === undefined) return false;
    return true;
}

export function ListSecretsResponseFromJSON(json: any): ListSecretsResponse {
    return ListSecretsResponseFromJSONTyped(json, false);
}

export function ListSecretsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSecretsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'secrets': ((json['secrets'] as Array<any>).map(SecretMetadataResponseFromJSON)),
    };
}

export function ListSecretsResponseToJSON(json: any): ListSecretsResponse {
    return ListSecretsResponseToJSONTyped(json, false);
}

export function ListSecretsResponseToJSONTyped(value?: ListSecretsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secrets': ((value['secrets'] as Array<any>).map(SecretMetadataResponseToJSON)),
    };
}

