/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IndexInfoResponse } from './IndexInfoResponse';
import {
    IndexInfoResponseFromJSON,
    IndexInfoResponseFromJSONTyped,
    IndexInfoResponseToJSON,
    IndexInfoResponseToJSONTyped,
} from './IndexInfoResponse';

/**
 * Response body for GET .../indexes
 * @export
 * @interface ListIndexesResponse
 */
export interface ListIndexesResponse {
    /**
     * 
     * @type {Array<IndexInfoResponse>}
     * @memberof ListIndexesResponse
     */
    indexes: Array<IndexInfoResponse>;
}

/**
 * Check if a given object implements the ListIndexesResponse interface.
 */
export function instanceOfListIndexesResponse(value: object): value is ListIndexesResponse {
    if (!('indexes' in value) || value['indexes'] === undefined) return false;
    return true;
}

export function ListIndexesResponseFromJSON(json: any): ListIndexesResponse {
    return ListIndexesResponseFromJSONTyped(json, false);
}

export function ListIndexesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIndexesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'indexes': ((json['indexes'] as Array<any>).map(IndexInfoResponseFromJSON)),
    };
}

export function ListIndexesResponseToJSON(json: any): ListIndexesResponse {
    return ListIndexesResponseToJSONTyped(json, false);
}

export function ListIndexesResponseToJSONTyped(value?: ListIndexesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'indexes': ((value['indexes'] as Array<any>).map(IndexInfoResponseToJSON)),
    };
}

