/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasetSummary } from './DatasetSummary';
import {
    DatasetSummaryFromJSON,
    DatasetSummaryFromJSONTyped,
    DatasetSummaryToJSON,
    DatasetSummaryToJSONTyped,
} from './DatasetSummary';

/**
 * Response body for GET /v1/datasets
 * @export
 * @interface ListDatasetsResponse
 */
export interface ListDatasetsResponse {
    /**
     * Number of datasets returned in this response
     * @type {number}
     * @memberof ListDatasetsResponse
     */
    count: number;
    /**
     * 
     * @type {Array<DatasetSummary>}
     * @memberof ListDatasetsResponse
     */
    datasets: Array<DatasetSummary>;
    /**
     * Whether there are more datasets available after this page
     * @type {boolean}
     * @memberof ListDatasetsResponse
     */
    hasMore: boolean;
    /**
     * Limit used for this request
     * @type {number}
     * @memberof ListDatasetsResponse
     */
    limit: number;
    /**
     * Pagination offset used for this request
     * @type {number}
     * @memberof ListDatasetsResponse
     */
    offset: number;
}

/**
 * Check if a given object implements the ListDatasetsResponse interface.
 */
export function instanceOfListDatasetsResponse(value: object): value is ListDatasetsResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('datasets' in value) || value['datasets'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListDatasetsResponseFromJSON(json: any): ListDatasetsResponse {
    return ListDatasetsResponseFromJSONTyped(json, false);
}

export function ListDatasetsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDatasetsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'datasets': ((json['datasets'] as Array<any>).map(DatasetSummaryFromJSON)),
        'hasMore': json['has_more'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function ListDatasetsResponseToJSON(json: any): ListDatasetsResponse {
    return ListDatasetsResponseToJSONTyped(json, false);
}

export function ListDatasetsResponseToJSONTyped(value?: ListDatasetsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'datasets': ((value['datasets'] as Array<any>).map(DatasetSummaryToJSON)),
        'has_more': value['hasMore'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

