/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceListItem } from './WorkspaceListItem';
import {
    WorkspaceListItemFromJSON,
    WorkspaceListItemFromJSONTyped,
    WorkspaceListItemToJSON,
    WorkspaceListItemToJSONTyped,
} from './WorkspaceListItem';

/**
 * 
 * @export
 * @interface ListWorkspacesResponse
 */
export interface ListWorkspacesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListWorkspacesResponse
     */
    ok: boolean;
    /**
     * 
     * @type {Array<WorkspaceListItem>}
     * @memberof ListWorkspacesResponse
     */
    workspaces: Array<WorkspaceListItem>;
}

/**
 * Check if a given object implements the ListWorkspacesResponse interface.
 */
export function instanceOfListWorkspacesResponse(value: object): value is ListWorkspacesResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('workspaces' in value) || value['workspaces'] === undefined) return false;
    return true;
}

export function ListWorkspacesResponseFromJSON(json: any): ListWorkspacesResponse {
    return ListWorkspacesResponseFromJSONTyped(json, false);
}

export function ListWorkspacesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkspacesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'workspaces': ((json['workspaces'] as Array<any>).map(WorkspaceListItemFromJSON)),
    };
}

export function ListWorkspacesResponseToJSON(json: any): ListWorkspacesResponse {
    return ListWorkspacesResponseToJSONTyped(json, false);
}

export function ListWorkspacesResponseToJSONTyped(value?: ListWorkspacesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'workspaces': ((value['workspaces'] as Array<any>).map(WorkspaceListItemToJSON)),
    };
}

