/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionTypeSummary } from './ConnectionTypeSummary';
import {
    ConnectionTypeSummaryFromJSON,
    ConnectionTypeSummaryFromJSONTyped,
    ConnectionTypeSummaryToJSON,
    ConnectionTypeSummaryToJSONTyped,
} from './ConnectionTypeSummary';

/**
 * 
 * @export
 * @interface ListConnectionTypesResponse
 */
export interface ListConnectionTypesResponse {
    /**
     * 
     * @type {Array<ConnectionTypeSummary>}
     * @memberof ListConnectionTypesResponse
     */
    connectionTypes: Array<ConnectionTypeSummary>;
}

/**
 * Check if a given object implements the ListConnectionTypesResponse interface.
 */
export function instanceOfListConnectionTypesResponse(value: object): value is ListConnectionTypesResponse {
    if (!('connectionTypes' in value) || value['connectionTypes'] === undefined) return false;
    return true;
}

export function ListConnectionTypesResponseFromJSON(json: any): ListConnectionTypesResponse {
    return ListConnectionTypesResponseFromJSONTyped(json, false);
}

export function ListConnectionTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConnectionTypesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionTypes': ((json['connection_types'] as Array<any>).map(ConnectionTypeSummaryFromJSON)),
    };
}

export function ListConnectionTypesResponseToJSON(json: any): ListConnectionTypesResponse {
    return ListConnectionTypesResponseToJSONTyped(json, false);
}

export function ListConnectionTypesResponseToJSONTyped(value?: ListConnectionTypesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_types': ((value['connectionTypes'] as Array<any>).map(ConnectionTypeSummaryToJSON)),
    };
}

