/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryRunInfo } from './QueryRunInfo';
import {
    QueryRunInfoFromJSON,
    QueryRunInfoFromJSONTyped,
    QueryRunInfoToJSON,
    QueryRunInfoToJSONTyped,
} from './QueryRunInfo';

/**
 * Response body for GET /query-runs
 * @export
 * @interface ListQueryRunsResponse
 */
export interface ListQueryRunsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListQueryRunsResponse
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListQueryRunsResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListQueryRunsResponse
     */
    limit: number;
    /**
     * 
     * @type {string}
     * @memberof ListQueryRunsResponse
     */
    nextCursor?: string | null;
    /**
     * 
     * @type {Array<QueryRunInfo>}
     * @memberof ListQueryRunsResponse
     */
    queryRuns: Array<QueryRunInfo>;
}

/**
 * Check if a given object implements the ListQueryRunsResponse interface.
 */
export function instanceOfListQueryRunsResponse(value: object): value is ListQueryRunsResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('queryRuns' in value) || value['queryRuns'] === undefined) return false;
    return true;
}

export function ListQueryRunsResponseFromJSON(json: any): ListQueryRunsResponse {
    return ListQueryRunsResponseFromJSONTyped(json, false);
}

export function ListQueryRunsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListQueryRunsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'hasMore': json['has_more'],
        'limit': json['limit'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'queryRuns': ((json['query_runs'] as Array<any>).map(QueryRunInfoFromJSON)),
    };
}

export function ListQueryRunsResponseToJSON(json: any): ListQueryRunsResponse {
    return ListQueryRunsResponseToJSONTyped(json, false);
}

export function ListQueryRunsResponseToJSONTyped(value?: ListQueryRunsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'has_more': value['hasMore'],
        'limit': value['limit'],
        'next_cursor': value['nextCursor'],
        'query_runs': ((value['queryRuns'] as Array<any>).map(QueryRunInfoToJSON)),
    };
}

