/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SavedQuerySummary } from './SavedQuerySummary';
import {
    SavedQuerySummaryFromJSON,
    SavedQuerySummaryFromJSONTyped,
    SavedQuerySummaryToJSON,
    SavedQuerySummaryToJSONTyped,
} from './SavedQuerySummary';

/**
 * Response body for GET /v1/queries
 * @export
 * @interface ListSavedQueriesResponse
 */
export interface ListSavedQueriesResponse {
    /**
     * 
     * @type {number}
     * @memberof ListSavedQueriesResponse
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListSavedQueriesResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListSavedQueriesResponse
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListSavedQueriesResponse
     */
    offset: number;
    /**
     * 
     * @type {Array<SavedQuerySummary>}
     * @memberof ListSavedQueriesResponse
     */
    queries: Array<SavedQuerySummary>;
}

/**
 * Check if a given object implements the ListSavedQueriesResponse interface.
 */
export function instanceOfListSavedQueriesResponse(value: object): value is ListSavedQueriesResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('queries' in value) || value['queries'] === undefined) return false;
    return true;
}

export function ListSavedQueriesResponseFromJSON(json: any): ListSavedQueriesResponse {
    return ListSavedQueriesResponseFromJSONTyped(json, false);
}

export function ListSavedQueriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSavedQueriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'hasMore': json['has_more'],
        'limit': json['limit'],
        'offset': json['offset'],
        'queries': ((json['queries'] as Array<any>).map(SavedQuerySummaryFromJSON)),
    };
}

export function ListSavedQueriesResponseToJSON(json: any): ListSavedQueriesResponse {
    return ListSavedQueriesResponseToJSONTyped(json, false);
}

export function ListSavedQueriesResponseToJSONTyped(value?: ListSavedQueriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'has_more': value['hasMore'],
        'limit': value['limit'],
        'offset': value['offset'],
        'queries': ((value['queries'] as Array<any>).map(SavedQuerySummaryToJSON)),
    };
}

