/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasetVersionSummary } from './DatasetVersionSummary';
import {
    DatasetVersionSummaryFromJSON,
    DatasetVersionSummaryFromJSONTyped,
    DatasetVersionSummaryToJSON,
    DatasetVersionSummaryToJSONTyped,
} from './DatasetVersionSummary';

/**
 * Response body for GET /v1/datasets/{id}/versions
 * @export
 * @interface ListDatasetVersionsResponse
 */
export interface ListDatasetVersionsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListDatasetVersionsResponse
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ListDatasetVersionsResponse
     */
    datasetId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListDatasetVersionsResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListDatasetVersionsResponse
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListDatasetVersionsResponse
     */
    offset: number;
    /**
     * 
     * @type {Array<DatasetVersionSummary>}
     * @memberof ListDatasetVersionsResponse
     */
    versions: Array<DatasetVersionSummary>;
}

/**
 * Check if a given object implements the ListDatasetVersionsResponse interface.
 */
export function instanceOfListDatasetVersionsResponse(value: object): value is ListDatasetVersionsResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('datasetId' in value) || value['datasetId'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    return true;
}

export function ListDatasetVersionsResponseFromJSON(json: any): ListDatasetVersionsResponse {
    return ListDatasetVersionsResponseFromJSONTyped(json, false);
}

export function ListDatasetVersionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDatasetVersionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'datasetId': json['dataset_id'],
        'hasMore': json['has_more'],
        'limit': json['limit'],
        'offset': json['offset'],
        'versions': ((json['versions'] as Array<any>).map(DatasetVersionSummaryFromJSON)),
    };
}

export function ListDatasetVersionsResponseToJSON(json: any): ListDatasetVersionsResponse {
    return ListDatasetVersionsResponseToJSONTyped(json, false);
}

export function ListDatasetVersionsResponseToJSONTyped(value?: ListDatasetVersionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'dataset_id': value['datasetId'],
        'has_more': value['hasMore'],
        'limit': value['limit'],
        'offset': value['offset'],
        'versions': ((value['versions'] as Array<any>).map(DatasetVersionSummaryToJSON)),
    };
}

