/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatusResponse } from './JobStatusResponse';
import {
    JobStatusResponseFromJSON,
    JobStatusResponseFromJSONTyped,
    JobStatusResponseToJSON,
    JobStatusResponseToJSONTyped,
} from './JobStatusResponse';

/**
 * Response body for GET /v1/jobs
 * @export
 * @interface ListJobsResponse
 */
export interface ListJobsResponse {
    /**
     * 
     * @type {Array<JobStatusResponse>}
     * @memberof ListJobsResponse
     */
    jobs: Array<JobStatusResponse>;
}

/**
 * Check if a given object implements the ListJobsResponse interface.
 */
export function instanceOfListJobsResponse(value: object): value is ListJobsResponse {
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    return true;
}

export function ListJobsResponseFromJSON(json: any): ListJobsResponse {
    return ListJobsResponseFromJSONTyped(json, false);
}

export function ListJobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListJobsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': ((json['jobs'] as Array<any>).map(JobStatusResponseFromJSON)),
    };
}

export function ListJobsResponseToJSON(json: any): ListJobsResponse {
    return ListJobsResponseToJSONTyped(json, false);
}

export function ListJobsResponseToJSONTyped(value?: ListJobsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': ((value['jobs'] as Array<any>).map(JobStatusResponseToJSON)),
    };
}

