/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultInfo } from './ResultInfo';
import {
    ResultInfoFromJSON,
    ResultInfoFromJSONTyped,
    ResultInfoToJSON,
    ResultInfoToJSONTyped,
} from './ResultInfo';

/**
 * Response body for GET /results
 * @export
 * @interface ListResultsResponse
 */
export interface ListResultsResponse {
    /**
     * Number of results returned in this response
     * @type {number}
     * @memberof ListResultsResponse
     */
    count: number;
    /**
     * Whether there are more results available after this page
     * @type {boolean}
     * @memberof ListResultsResponse
     */
    hasMore: boolean;
    /**
     * Limit used for this request
     * @type {number}
     * @memberof ListResultsResponse
     */
    limit: number;
    /**
     * Pagination offset used for this request
     * @type {number}
     * @memberof ListResultsResponse
     */
    offset: number;
    /**
     * 
     * @type {Array<ResultInfo>}
     * @memberof ListResultsResponse
     */
    results: Array<ResultInfo>;
}

/**
 * Check if a given object implements the ListResultsResponse interface.
 */
export function instanceOfListResultsResponse(value: object): value is ListResultsResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ListResultsResponseFromJSON(json: any): ListResultsResponse {
    return ListResultsResponseFromJSONTyped(json, false);
}

export function ListResultsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResultsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'hasMore': json['has_more'],
        'limit': json['limit'],
        'offset': json['offset'],
        'results': ((json['results'] as Array<any>).map(ResultInfoFromJSON)),
    };
}

export function ListResultsResponseToJSON(json: any): ListResultsResponse {
    return ListResultsResponseToJSONTyped(json, false);
}

export function ListResultsResponseToJSONTyped(value?: ListResultsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'has_more': value['hasMore'],
        'limit': value['limit'],
        'offset': value['offset'],
        'results': ((value['results'] as Array<any>).map(ResultInfoToJSON)),
    };
}

