/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionInfo } from './ConnectionInfo';
import {
    ConnectionInfoFromJSON,
    ConnectionInfoFromJSONTyped,
    ConnectionInfoToJSON,
    ConnectionInfoToJSONTyped,
} from './ConnectionInfo';

/**
 * Response body for GET /connections
 * @export
 * @interface ListConnectionsResponse
 */
export interface ListConnectionsResponse {
    /**
     * 
     * @type {Array<ConnectionInfo>}
     * @memberof ListConnectionsResponse
     */
    connections: Array<ConnectionInfo>;
}

/**
 * Check if a given object implements the ListConnectionsResponse interface.
 */
export function instanceOfListConnectionsResponse(value: object): value is ListConnectionsResponse {
    if (!('connections' in value) || value['connections'] === undefined) return false;
    return true;
}

export function ListConnectionsResponseFromJSON(json: any): ListConnectionsResponse {
    return ListConnectionsResponseFromJSONTyped(json, false);
}

export function ListConnectionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConnectionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connections': ((json['connections'] as Array<any>).map(ConnectionInfoFromJSON)),
    };
}

export function ListConnectionsResponseToJSON(json: any): ListConnectionsResponse {
    return ListConnectionsResponseToJSONTyped(json, false);
}

export function ListConnectionsResponseToJSONTyped(value?: ListConnectionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connections': ((value['connections'] as Array<any>).map(ConnectionInfoToJSON)),
    };
}

