/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmbeddingProviderResponse } from './EmbeddingProviderResponse';
import {
    EmbeddingProviderResponseFromJSON,
    EmbeddingProviderResponseFromJSONTyped,
    EmbeddingProviderResponseToJSON,
    EmbeddingProviderResponseToJSONTyped,
} from './EmbeddingProviderResponse';

/**
 * Response body for GET /embedding-providers
 * @export
 * @interface ListEmbeddingProvidersResponse
 */
export interface ListEmbeddingProvidersResponse {
    /**
     * 
     * @type {Array<EmbeddingProviderResponse>}
     * @memberof ListEmbeddingProvidersResponse
     */
    embeddingProviders: Array<EmbeddingProviderResponse>;
}

/**
 * Check if a given object implements the ListEmbeddingProvidersResponse interface.
 */
export function instanceOfListEmbeddingProvidersResponse(value: object): value is ListEmbeddingProvidersResponse {
    if (!('embeddingProviders' in value) || value['embeddingProviders'] === undefined) return false;
    return true;
}

export function ListEmbeddingProvidersResponseFromJSON(json: any): ListEmbeddingProvidersResponse {
    return ListEmbeddingProvidersResponseFromJSONTyped(json, false);
}

export function ListEmbeddingProvidersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEmbeddingProvidersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'embeddingProviders': ((json['embedding_providers'] as Array<any>).map(EmbeddingProviderResponseFromJSON)),
    };
}

export function ListEmbeddingProvidersResponseToJSON(json: any): ListEmbeddingProvidersResponse {
    return ListEmbeddingProvidersResponseToJSONTyped(json, false);
}

export function ListEmbeddingProvidersResponseToJSONTyped(value?: ListEmbeddingProvidersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'embedding_providers': ((value['embeddingProviders'] as Array<any>).map(EmbeddingProviderResponseToJSON)),
    };
}

