/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * High-cardinality numeric column (>200 distinct values).
 * @export
 * @interface NumericProfileDetail
 */
export interface NumericProfileDetail {
    /**
     * Maximum value (string to preserve precision for large integers and decimals)
     * @type {string}
     * @memberof NumericProfileDetail
     */
    max: string;
    /**
     * Arithmetic mean
     * @type {number}
     * @memberof NumericProfileDetail
     */
    mean: number;
    /**
     * Minimum value (string to preserve precision for large integers and decimals)
     * @type {string}
     * @memberof NumericProfileDetail
     */
    min: string;
}

/**
 * Check if a given object implements the NumericProfileDetail interface.
 */
export function instanceOfNumericProfileDetail(value: object): value is NumericProfileDetail {
    if (!('max' in value) || value['max'] === undefined) return false;
    if (!('mean' in value) || value['mean'] === undefined) return false;
    if (!('min' in value) || value['min'] === undefined) return false;
    return true;
}

export function NumericProfileDetailFromJSON(json: any): NumericProfileDetail {
    return NumericProfileDetailFromJSONTyped(json, false);
}

export function NumericProfileDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumericProfileDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'max': json['max'],
        'mean': json['mean'],
        'min': json['min'],
    };
}

export function NumericProfileDetailToJSON(json: any): NumericProfileDetail {
    return NumericProfileDetailToJSONTyped(json, false);
}

export function NumericProfileDetailToJSONTyped(value?: NumericProfileDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max': value['max'],
        'mean': value['mean'],
        'min': value['min'],
    };
}

