/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /query
 * @export
 * @interface QueryRequest
 */
export interface QueryRequest {
    /**
     * 
     * @type {string}
     * @memberof QueryRequest
     */
    sql: string;
}

/**
 * Check if a given object implements the QueryRequest interface.
 */
export function instanceOfQueryRequest(value: object): value is QueryRequest {
    if (!('sql' in value) || value['sql'] === undefined) return false;
    return true;
}

export function QueryRequestFromJSON(json: any): QueryRequest {
    return QueryRequestFromJSONTyped(json, false);
}

export function QueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sql': json['sql'],
    };
}

export function QueryRequestToJSON(json: any): QueryRequest {
    return QueryRequestToJSONTyped(json, false);
}

export function QueryRequestToJSONTyped(value?: QueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sql': value['sql'],
    };
}

