/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /query
 * @export
 * @interface QueryRequest
 */
export interface QueryRequest {
    /**
     * When true, execute the query asynchronously and return a query run ID for polling
     * via GET /query-runs/{id}. The query results can be retrieved via GET /results/{id}
     * once the query run status is "succeeded".
     * @type {boolean}
     * @memberof QueryRequest
     */
    async?: boolean;
    /**
     * If set with async=true, wait up to this many milliseconds for the query to complete
     * synchronously before returning an async response. Minimum 1000ms.
     * Ignored if async is false.
     * @type {number}
     * @memberof QueryRequest
     */
    asyncAfterMs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof QueryRequest
     */
    sql: string;
}

/**
 * Check if a given object implements the QueryRequest interface.
 */
export function instanceOfQueryRequest(value: object): value is QueryRequest {
    if (!('sql' in value) || value['sql'] === undefined) return false;
    return true;
}

export function QueryRequestFromJSON(json: any): QueryRequest {
    return QueryRequestFromJSONTyped(json, false);
}

export function QueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'async': json['async'] == null ? undefined : json['async'],
        'asyncAfterMs': json['async_after_ms'] == null ? undefined : json['async_after_ms'],
        'sql': json['sql'],
    };
}

export function QueryRequestToJSON(json: any): QueryRequest {
    return QueryRequestToJSONTyped(json, false);
}

export function QueryRequestToJSONTyped(value?: QueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'async': value['async'],
        'async_after_ms': value['asyncAfterMs'],
        'sql': value['sql'],
    };
}

