/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single query run for listing
 * @export
 * @interface QueryRunInfo
 */
export interface QueryRunInfo {
    /**
     * 
     * @type {Date}
     * @memberof QueryRunInfo
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof QueryRunInfo
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof QueryRunInfo
     */
    executionTimeMs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    resultId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof QueryRunInfo
     */
    rowCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    savedQueryId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof QueryRunInfo
     */
    savedQueryVersion?: number | null;
    /**
     * Total server-side processing time for this query (milliseconds).
     * Measured from query start to result ready. Includes SQL execution,
     * task spawning, and result preparation. Does not include network transit.
     * Populated for all completed query runs (sync and async).
     * @type {number}
     * @memberof QueryRunInfo
     */
    serverProcessingMs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    snapshotId: string;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    sqlHash: string;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    sqlText: string;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    traceId?: string | null;
    /**
     * Caller identity derived from the Authorization Bearer token (SHA-256 hash).
     * Format: `user_{first_10_hex_chars}`. Mirrors the webapp's `user_public_id_from_auth_header`.
     * @type {string}
     * @memberof QueryRunInfo
     */
    userPublicId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryRunInfo
     */
    warningMessage?: string | null;
}

/**
 * Check if a given object implements the QueryRunInfo interface.
 */
export function instanceOfQueryRunInfo(value: object): value is QueryRunInfo {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('snapshotId' in value) || value['snapshotId'] === undefined) return false;
    if (!('sqlHash' in value) || value['sqlHash'] === undefined) return false;
    if (!('sqlText' in value) || value['sqlText'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function QueryRunInfoFromJSON(json: any): QueryRunInfo {
    return QueryRunInfoFromJSONTyped(json, false);
}

export function QueryRunInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRunInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'createdAt': (new Date(json['created_at'])),
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'executionTimeMs': json['execution_time_ms'] == null ? undefined : json['execution_time_ms'],
        'id': json['id'],
        'resultId': json['result_id'] == null ? undefined : json['result_id'],
        'rowCount': json['row_count'] == null ? undefined : json['row_count'],
        'savedQueryId': json['saved_query_id'] == null ? undefined : json['saved_query_id'],
        'savedQueryVersion': json['saved_query_version'] == null ? undefined : json['saved_query_version'],
        'serverProcessingMs': json['server_processing_ms'] == null ? undefined : json['server_processing_ms'],
        'snapshotId': json['snapshot_id'],
        'sqlHash': json['sql_hash'],
        'sqlText': json['sql_text'],
        'status': json['status'],
        'traceId': json['trace_id'] == null ? undefined : json['trace_id'],
        'userPublicId': json['user_public_id'] == null ? undefined : json['user_public_id'],
        'warningMessage': json['warning_message'] == null ? undefined : json['warning_message'],
    };
}

export function QueryRunInfoToJSON(json: any): QueryRunInfo {
    return QueryRunInfoToJSONTyped(json, false);
}

export function QueryRunInfoToJSONTyped(value?: QueryRunInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
        'error_message': value['errorMessage'],
        'execution_time_ms': value['executionTimeMs'],
        'id': value['id'],
        'result_id': value['resultId'],
        'row_count': value['rowCount'],
        'saved_query_id': value['savedQueryId'],
        'saved_query_version': value['savedQueryVersion'],
        'server_processing_ms': value['serverProcessingMs'],
        'snapshot_id': value['snapshotId'],
        'sql_hash': value['sqlHash'],
        'sql_text': value['sqlText'],
        'status': value['status'],
        'trace_id': value['traceId'],
        'user_public_id': value['userPublicId'],
        'warning_message': value['warningMessage'],
    };
}

