/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /query
 * 
 * Query results are returned immediately along with a `result_id` for later retrieval.
 * The actual persistence to storage happens asynchronously in the background.
 * 
 * To check if a result is ready for SQL queries, poll GET /results/{id} and check `status`:
 * - `"processing"`: Persistence is still in progress
 * - `"ready"`: Result is available for retrieval and SQL queries
 * - `"failed"`: Persistence failed (check `error_message` for details)
 * @export
 * @interface QueryResponse
 */
export interface QueryResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryResponse
     */
    columns: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof QueryResponse
     */
    executionTimeMs: number;
    /**
     * Nullable flags for each column (parallel to columns vec).
     * True if the column allows NULL values, false if NOT NULL.
     * @type {Array<boolean>}
     * @memberof QueryResponse
     */
    nullable: Array<boolean>;
    /**
     * Unique identifier for the query run record (qrun...).
     * @type {string}
     * @memberof QueryResponse
     */
    queryRunId: string;
    /**
     * Unique identifier for retrieving this result via GET /results/{id}.
     * Null if catalog registration failed (see `warning` field for details).
     * When non-null, the result is being persisted asynchronously.
     * @type {string}
     * @memberof QueryResponse
     */
    resultId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof QueryResponse
     */
    rowCount: number;
    /**
     * Array of rows, where each row is an array of column values.
     * Values can be strings, numbers, booleans, or null.
     * @type {Array<Array<any>>}
     * @memberof QueryResponse
     */
    rows: Array<Array<any>>;
    /**
     * Warning message if result persistence could not be initiated.
     * When present, `result_id` will be null and the result cannot be retrieved later.
     * The query results are still returned in this response.
     * @type {string}
     * @memberof QueryResponse
     */
    warning?: string | null;
}

/**
 * Check if a given object implements the QueryResponse interface.
 */
export function instanceOfQueryResponse(value: object): value is QueryResponse {
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('executionTimeMs' in value) || value['executionTimeMs'] === undefined) return false;
    if (!('nullable' in value) || value['nullable'] === undefined) return false;
    if (!('queryRunId' in value) || value['queryRunId'] === undefined) return false;
    if (!('rowCount' in value) || value['rowCount'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    return true;
}

export function QueryResponseFromJSON(json: any): QueryResponse {
    return QueryResponseFromJSONTyped(json, false);
}

export function QueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'],
        'executionTimeMs': json['execution_time_ms'],
        'nullable': json['nullable'],
        'queryRunId': json['query_run_id'],
        'resultId': json['result_id'] == null ? undefined : json['result_id'],
        'rowCount': json['row_count'],
        'rows': json['rows'],
        'warning': json['warning'] == null ? undefined : json['warning'],
    };
}

export function QueryResponseToJSON(json: any): QueryResponse {
    return QueryResponseToJSONTyped(json, false);
}

export function QueryResponseToJSONTyped(value?: QueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'],
        'execution_time_ms': value['executionTimeMs'],
        'nullable': value['nullable'],
        'query_run_id': value['queryRunId'],
        'result_id': value['resultId'],
        'row_count': value['rowCount'],
        'rows': value['rows'],
        'warning': value['warning'],
    };
}

