/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConnectionRefreshResult } from './ConnectionRefreshResult';
import {
    instanceOfConnectionRefreshResult,
    ConnectionRefreshResultFromJSON,
    ConnectionRefreshResultFromJSONTyped,
    ConnectionRefreshResultToJSON,
} from './ConnectionRefreshResult';
import type { RefreshDatasetResponse } from './RefreshDatasetResponse';
import {
    instanceOfRefreshDatasetResponse,
    RefreshDatasetResponseFromJSON,
    RefreshDatasetResponseFromJSONTyped,
    RefreshDatasetResponseToJSON,
} from './RefreshDatasetResponse';
import type { SchemaRefreshResult } from './SchemaRefreshResult';
import {
    instanceOfSchemaRefreshResult,
    SchemaRefreshResultFromJSON,
    SchemaRefreshResultFromJSONTyped,
    SchemaRefreshResultToJSON,
} from './SchemaRefreshResult';
import type { SubmitJobResponse } from './SubmitJobResponse';
import {
    instanceOfSubmitJobResponse,
    SubmitJobResponseFromJSON,
    SubmitJobResponseFromJSONTyped,
    SubmitJobResponseToJSON,
} from './SubmitJobResponse';
import type { TableRefreshResult } from './TableRefreshResult';
import {
    instanceOfTableRefreshResult,
    TableRefreshResultFromJSON,
    TableRefreshResultFromJSONTyped,
    TableRefreshResultToJSON,
} from './TableRefreshResult';

/**
 * @type RefreshResponse
 * Unified response type for refresh operations
 * @export
 */
export type RefreshResponse = ConnectionRefreshResult | RefreshDatasetResponse | SchemaRefreshResult | SubmitJobResponse | TableRefreshResult;

export function RefreshResponseFromJSON(json: any): RefreshResponse {
    return RefreshResponseFromJSONTyped(json, false);
}

export function RefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfConnectionRefreshResult(json)) {
        return ConnectionRefreshResultFromJSONTyped(json, true);
    }
    if (instanceOfRefreshDatasetResponse(json)) {
        return RefreshDatasetResponseFromJSONTyped(json, true);
    }
    if (instanceOfSchemaRefreshResult(json)) {
        return SchemaRefreshResultFromJSONTyped(json, true);
    }
    if (instanceOfSubmitJobResponse(json)) {
        return SubmitJobResponseFromJSONTyped(json, true);
    }
    if (instanceOfTableRefreshResult(json)) {
        return TableRefreshResultFromJSONTyped(json, true);
    }
    return {} as any;
}

export function RefreshResponseToJSON(json: any): any {
    return RefreshResponseToJSONTyped(json, false);
}

export function RefreshResponseToJSONTyped(value?: RefreshResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfConnectionRefreshResult(value)) {
        return ConnectionRefreshResultToJSON(value as ConnectionRefreshResult);
    }
    if (instanceOfRefreshDatasetResponse(value)) {
        return RefreshDatasetResponseToJSON(value as RefreshDatasetResponse);
    }
    if (instanceOfSchemaRefreshResult(value)) {
        return SchemaRefreshResultToJSON(value as SchemaRefreshResult);
    }
    if (instanceOfSubmitJobResponse(value)) {
        return SubmitJobResponseToJSON(value as SubmitJobResponse);
    }
    if (instanceOfTableRefreshResult(value)) {
        return TableRefreshResultToJSON(value as TableRefreshResult);
    }
    return {};
}

