/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Non-fatal warning that occurred during a refresh operation.
 * Used to report issues like failed deletion scheduling that don't
 * prevent the refresh from succeeding.
 * @export
 * @interface RefreshWarning
 */
export interface RefreshWarning {
    /**
     * 
     * @type {string}
     * @memberof RefreshWarning
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof RefreshWarning
     */
    schemaName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RefreshWarning
     */
    tableName?: string | null;
}

/**
 * Check if a given object implements the RefreshWarning interface.
 */
export function instanceOfRefreshWarning(value: object): value is RefreshWarning {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function RefreshWarningFromJSON(json: any): RefreshWarning {
    return RefreshWarningFromJSONTyped(json, false);
}

export function RefreshWarningFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshWarning {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'schemaName': json['schema_name'] == null ? undefined : json['schema_name'],
        'tableName': json['table_name'] == null ? undefined : json['table_name'],
    };
}

export function RefreshWarningToJSON(json: any): RefreshWarning {
    return RefreshWarningToJSONTyped(json, false);
}

export function RefreshWarningToJSONTyped(value?: RefreshWarning | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'schema_name': value['schemaName'],
        'table_name': value['tableName'],
    };
}

