/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /v1/datasets/{id}/refresh
 * @export
 * @interface RefreshDatasetResponse
 */
export interface RefreshDatasetResponse {
    /**
     * 
     * @type {Date}
     * @memberof RefreshDatasetResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RefreshDatasetResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RefreshDatasetResponse
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof RefreshDatasetResponse
     */
    version: number;
}

/**
 * Check if a given object implements the RefreshDatasetResponse interface.
 */
export function instanceOfRefreshDatasetResponse(value: object): value is RefreshDatasetResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function RefreshDatasetResponseFromJSON(json: any): RefreshDatasetResponse {
    return RefreshDatasetResponseFromJSONTyped(json, false);
}

export function RefreshDatasetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshDatasetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'status': json['status'],
        'version': json['version'],
    };
}

export function RefreshDatasetResponseToJSON(json: any): RefreshDatasetResponse {
    return RefreshDatasetResponseToJSONTyped(json, false);
}

export function RefreshDatasetResponseToJSONTyped(value?: RefreshDatasetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'status': value['status'],
        'version': value['version'],
    };
}

