/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /refresh
 * @export
 * @interface RefreshRequest
 */
export interface RefreshRequest {
    /**
     * 
     * @type {string}
     * @memberof RefreshRequest
     */
    connectionId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RefreshRequest
     */
    data?: boolean;
    /**
     * Controls whether uncached tables are included in connection-wide data refresh.
     * 
     * - `false` (default): Only refresh tables that already have cached data.
     *   This is the common case for keeping existing data up-to-date.
     * - `true`: Also sync tables that haven't been cached yet, essentially performing
     *   an initial sync for any new tables discovered since the connection was created.
     * 
     * This field only applies to connection-wide data refresh (when `data=true` and
     * `table_name` is not specified). It has no effect on single-table refresh or
     * schema refresh operations.
     * @type {boolean}
     * @memberof RefreshRequest
     */
    includeUncached?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RefreshRequest
     */
    schemaName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RefreshRequest
     */
    tableName?: string | null;
}

/**
 * Check if a given object implements the RefreshRequest interface.
 */
export function instanceOfRefreshRequest(value: object): value is RefreshRequest {
    return true;
}

export function RefreshRequestFromJSON(json: any): RefreshRequest {
    return RefreshRequestFromJSONTyped(json, false);
}

export function RefreshRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connection_id'] == null ? undefined : json['connection_id'],
        'data': json['data'] == null ? undefined : json['data'],
        'includeUncached': json['include_uncached'] == null ? undefined : json['include_uncached'],
        'schemaName': json['schema_name'] == null ? undefined : json['schema_name'],
        'tableName': json['table_name'] == null ? undefined : json['table_name'],
    };
}

export function RefreshRequestToJSON(json: any): RefreshRequest {
    return RefreshRequestToJSONTyped(json, false);
}

export function RefreshRequestToJSONTyped(value?: RefreshRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_id': value['connectionId'],
        'data': value['data'],
        'include_uncached': value['includeUncached'],
        'schema_name': value['schemaName'],
        'table_name': value['tableName'],
    };
}

