/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary of a persisted query result for listing
 * @export
 * @interface ResultInfo
 */
export interface ResultInfo {
    /**
     * 
     * @type {Date}
     * @memberof ResultInfo
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ResultInfo
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResultInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ResultInfo
     */
    status: string;
}

/**
 * Check if a given object implements the ResultInfo interface.
 */
export function instanceOfResultInfo(value: object): value is ResultInfo {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ResultInfoFromJSON(json: any): ResultInfo {
    return ResultInfoFromJSONTyped(json, false);
}

export function ResultInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'id': json['id'],
        'status': json['status'],
    };
}

export function ResultInfoToJSON(json: any): ResultInfo {
    return ResultInfoToJSONTyped(json, false);
}

export function ResultInfoToJSONTyped(value?: ResultInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'error_message': value['errorMessage'],
        'id': value['id'],
        'status': value['status'],
    };
}

