/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sandbox
 */
export interface Sandbox {
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    publicId: string;
    /**
     * 
     * @type {string}
     * @memberof Sandbox
     */
    name: string;
    /**
     * Freeform markdown notes attached to the sandbox.
     * @type {string}
     * @memberof Sandbox
     */
    markdown: string;
    /**
     * 
     * @type {Date}
     * @memberof Sandbox
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Sandbox
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Sandbox interface.
 */
export function instanceOfSandbox(value: object): value is Sandbox {
    if (!('publicId' in value) || value['publicId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('markdown' in value) || value['markdown'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SandboxFromJSON(json: any): Sandbox {
    return SandboxFromJSONTyped(json, false);
}

export function SandboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sandbox {
    if (json == null) {
        return json;
    }
    return {
        
        'publicId': json['public_id'],
        'name': json['name'],
        'markdown': json['markdown'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SandboxToJSON(json: any): Sandbox {
    return SandboxToJSONTyped(json, false);
}

export function SandboxToJSONTyped(value?: Sandbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_id': value['publicId'],
        'name': value['name'],
        'markdown': value['markdown'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

