/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sandbox } from './Sandbox';
import {
    SandboxFromJSON,
    SandboxFromJSONTyped,
    SandboxToJSON,
    SandboxToJSONTyped,
} from './Sandbox';

/**
 * 
 * @export
 * @interface SandboxResponse
 */
export interface SandboxResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SandboxResponse
     */
    ok: boolean;
    /**
     * 
     * @type {Sandbox}
     * @memberof SandboxResponse
     */
    sandbox: Sandbox;
}

/**
 * Check if a given object implements the SandboxResponse interface.
 */
export function instanceOfSandboxResponse(value: object): value is SandboxResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('sandbox' in value) || value['sandbox'] === undefined) return false;
    return true;
}

export function SandboxResponseFromJSON(json: any): SandboxResponse {
    return SandboxResponseFromJSONTyped(json, false);
}

export function SandboxResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SandboxResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'sandbox': SandboxFromJSON(json['sandbox']),
    };
}

export function SandboxResponseToJSON(json: any): SandboxResponse {
    return SandboxResponseToJSONTyped(json, false);
}

export function SandboxResponseToJSONTyped(value?: SandboxResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'sandbox': SandboxToJSON(value['sandbox']),
    };
}

