/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Saved query summary for listing
 * @export
 * @interface SavedQuerySummary
 */
export interface SavedQuerySummary {
    /**
     * 
     * @type {Date}
     * @memberof SavedQuerySummary
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SavedQuerySummary
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof SavedQuerySummary
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof SavedQuerySummary
     */
    latestVersion: number;
    /**
     * 
     * @type {string}
     * @memberof SavedQuerySummary
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SavedQuerySummary
     */
    tags: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof SavedQuerySummary
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the SavedQuerySummary interface.
 */
export function instanceOfSavedQuerySummary(value: object): value is SavedQuerySummary {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('latestVersion' in value) || value['latestVersion'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SavedQuerySummaryFromJSON(json: any): SavedQuerySummary {
    return SavedQuerySummaryFromJSONTyped(json, false);
}

export function SavedQuerySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavedQuerySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'],
        'id': json['id'],
        'latestVersion': json['latest_version'],
        'name': json['name'],
        'tags': json['tags'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SavedQuerySummaryToJSON(json: any): SavedQuerySummary {
    return SavedQuerySummaryToJSONTyped(json, false);
}

export function SavedQuerySummaryToJSONTyped(value?: SavedQuerySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'description': value['description'],
        'id': value['id'],
        'latest_version': value['latestVersion'],
        'name': value['name'],
        'tags': value['tags'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

