/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create dataset from a saved query result
 * @export
 * @interface SavedQueryDatasetSource
 */
export interface SavedQueryDatasetSource {
    /**
     * 
     * @type {string}
     * @memberof SavedQueryDatasetSource
     */
    savedQueryId: string;
    /**
     * 
     * @type {number}
     * @memberof SavedQueryDatasetSource
     */
    version?: number | null;
}

/**
 * Check if a given object implements the SavedQueryDatasetSource interface.
 */
export function instanceOfSavedQueryDatasetSource(value: object): value is SavedQueryDatasetSource {
    if (!('savedQueryId' in value) || value['savedQueryId'] === undefined) return false;
    return true;
}

export function SavedQueryDatasetSourceFromJSON(json: any): SavedQueryDatasetSource {
    return SavedQueryDatasetSourceFromJSONTyped(json, false);
}

export function SavedQueryDatasetSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavedQueryDatasetSource {
    if (json == null) {
        return json;
    }
    return {
        
        'savedQueryId': json['saved_query_id'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function SavedQueryDatasetSourceToJSON(json: any): SavedQueryDatasetSource {
    return SavedQueryDatasetSourceToJSONTyped(json, false);
}

export function SavedQueryDatasetSourceToJSONTyped(value?: SavedQueryDatasetSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'saved_query_id': value['savedQueryId'],
        'version': value['version'],
    };
}

