/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Saved query detail (includes latest version's SQL)
 * @export
 * @interface SavedQueryDetail
 */
export interface SavedQueryDetail {
    /**
     * 
     * @type {string}
     * @memberof SavedQueryDetail
     */
    category?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SavedQueryDetail
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SavedQueryDetail
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof SavedQueryDetail
     */
    hasAggregation?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SavedQueryDetail
     */
    hasGroupBy?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SavedQueryDetail
     */
    hasJoin?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SavedQueryDetail
     */
    hasLimit?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SavedQueryDetail
     */
    hasOrderBy?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SavedQueryDetail
     */
    hasPredicate?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof SavedQueryDetail
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof SavedQueryDetail
     */
    latestVersion: number;
    /**
     * 
     * @type {string}
     * @memberof SavedQueryDetail
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SavedQueryDetail
     */
    numTables?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SavedQueryDetail
     */
    sql: string;
    /**
     * 
     * @type {string}
     * @memberof SavedQueryDetail
     */
    sqlHash: string;
    /**
     * 
     * @type {string}
     * @memberof SavedQueryDetail
     */
    tableSize?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SavedQueryDetail
     */
    tags: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof SavedQueryDetail
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the SavedQueryDetail interface.
 */
export function instanceOfSavedQueryDetail(value: object): value is SavedQueryDetail {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('latestVersion' in value) || value['latestVersion'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sql' in value) || value['sql'] === undefined) return false;
    if (!('sqlHash' in value) || value['sqlHash'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SavedQueryDetailFromJSON(json: any): SavedQueryDetail {
    return SavedQueryDetailFromJSONTyped(json, false);
}

export function SavedQueryDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavedQueryDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'],
        'hasAggregation': json['has_aggregation'] == null ? undefined : json['has_aggregation'],
        'hasGroupBy': json['has_group_by'] == null ? undefined : json['has_group_by'],
        'hasJoin': json['has_join'] == null ? undefined : json['has_join'],
        'hasLimit': json['has_limit'] == null ? undefined : json['has_limit'],
        'hasOrderBy': json['has_order_by'] == null ? undefined : json['has_order_by'],
        'hasPredicate': json['has_predicate'] == null ? undefined : json['has_predicate'],
        'id': json['id'],
        'latestVersion': json['latest_version'],
        'name': json['name'],
        'numTables': json['num_tables'] == null ? undefined : json['num_tables'],
        'sql': json['sql'],
        'sqlHash': json['sql_hash'],
        'tableSize': json['table_size'] == null ? undefined : json['table_size'],
        'tags': json['tags'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SavedQueryDetailToJSON(json: any): SavedQueryDetail {
    return SavedQueryDetailToJSONTyped(json, false);
}

export function SavedQueryDetailToJSONTyped(value?: SavedQueryDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'created_at': value['createdAt'].toISOString(),
        'description': value['description'],
        'has_aggregation': value['hasAggregation'],
        'has_group_by': value['hasGroupBy'],
        'has_join': value['hasJoin'],
        'has_limit': value['hasLimit'],
        'has_order_by': value['hasOrderBy'],
        'has_predicate': value['hasPredicate'],
        'id': value['id'],
        'latest_version': value['latestVersion'],
        'name': value['name'],
        'num_tables': value['numTables'],
        'sql': value['sql'],
        'sql_hash': value['sqlHash'],
        'table_size': value['tableSize'],
        'tags': value['tags'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

