/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionSchemaError } from './ConnectionSchemaError';
import {
    ConnectionSchemaErrorFromJSON,
    ConnectionSchemaErrorFromJSONTyped,
    ConnectionSchemaErrorToJSON,
    ConnectionSchemaErrorToJSONTyped,
} from './ConnectionSchemaError';

/**
 * Response for schema refresh operations
 * @export
 * @interface SchemaRefreshResult
 */
export interface SchemaRefreshResult {
    /**
     * 
     * @type {number}
     * @memberof SchemaRefreshResult
     */
    connectionsFailed: number;
    /**
     * 
     * @type {number}
     * @memberof SchemaRefreshResult
     */
    connectionsRefreshed: number;
    /**
     * 
     * @type {Array<ConnectionSchemaError>}
     * @memberof SchemaRefreshResult
     */
    errors?: Array<ConnectionSchemaError>;
    /**
     * 
     * @type {number}
     * @memberof SchemaRefreshResult
     */
    tablesAdded: number;
    /**
     * 
     * @type {number}
     * @memberof SchemaRefreshResult
     */
    tablesDiscovered: number;
    /**
     * 
     * @type {number}
     * @memberof SchemaRefreshResult
     */
    tablesModified: number;
}

/**
 * Check if a given object implements the SchemaRefreshResult interface.
 */
export function instanceOfSchemaRefreshResult(value: object): value is SchemaRefreshResult {
    if (!('connectionsFailed' in value) || value['connectionsFailed'] === undefined) return false;
    if (!('connectionsRefreshed' in value) || value['connectionsRefreshed'] === undefined) return false;
    if (!('tablesAdded' in value) || value['tablesAdded'] === undefined) return false;
    if (!('tablesDiscovered' in value) || value['tablesDiscovered'] === undefined) return false;
    if (!('tablesModified' in value) || value['tablesModified'] === undefined) return false;
    return true;
}

export function SchemaRefreshResultFromJSON(json: any): SchemaRefreshResult {
    return SchemaRefreshResultFromJSONTyped(json, false);
}

export function SchemaRefreshResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaRefreshResult {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionsFailed': json['connections_failed'],
        'connectionsRefreshed': json['connections_refreshed'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ConnectionSchemaErrorFromJSON)),
        'tablesAdded': json['tables_added'],
        'tablesDiscovered': json['tables_discovered'],
        'tablesModified': json['tables_modified'],
    };
}

export function SchemaRefreshResultToJSON(json: any): SchemaRefreshResult {
    return SchemaRefreshResultToJSONTyped(json, false);
}

export function SchemaRefreshResultToJSONTyped(value?: SchemaRefreshResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connections_failed': value['connectionsFailed'],
        'connections_refreshed': value['connectionsRefreshed'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ConnectionSchemaErrorToJSON)),
        'tables_added': value['tablesAdded'],
        'tables_discovered': value['tablesDiscovered'],
        'tables_modified': value['tablesModified'],
    };
}

