/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single secret metadata for API responses
 * @export
 * @interface SecretMetadataResponse
 */
export interface SecretMetadataResponse {
    /**
     * 
     * @type {Date}
     * @memberof SecretMetadataResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SecretMetadataResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof SecretMetadataResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the SecretMetadataResponse interface.
 */
export function instanceOfSecretMetadataResponse(value: object): value is SecretMetadataResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SecretMetadataResponseFromJSON(json: any): SecretMetadataResponse {
    return SecretMetadataResponseFromJSONTyped(json, false);
}

export function SecretMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SecretMetadataResponseToJSON(json: any): SecretMetadataResponse {
    return SecretMetadataResponseToJSONTyped(json, false);
}

export function SecretMetadataResponseToJSONTyped(value?: SecretMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'name': value['name'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

