/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create dataset from a SQL query (auto-creates a saved query)
 * @export
 * @interface SqlQueryDatasetSource
 */
export interface SqlQueryDatasetSource {
    /**
     * Optional description for the auto-created saved query.
     * @type {string}
     * @memberof SqlQueryDatasetSource
     */
    description?: string | null;
    /**
     * Optional name for the auto-created saved query. Defaults to the dataset label.
     * @type {string}
     * @memberof SqlQueryDatasetSource
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SqlQueryDatasetSource
     */
    sql: string;
}

/**
 * Check if a given object implements the SqlQueryDatasetSource interface.
 */
export function instanceOfSqlQueryDatasetSource(value: object): value is SqlQueryDatasetSource {
    if (!('sql' in value) || value['sql'] === undefined) return false;
    return true;
}

export function SqlQueryDatasetSourceFromJSON(json: any): SqlQueryDatasetSource {
    return SqlQueryDatasetSourceFromJSONTyped(json, false);
}

export function SqlQueryDatasetSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SqlQueryDatasetSource {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'sql': json['sql'],
    };
}

export function SqlQueryDatasetSourceToJSON(json: any): SqlQueryDatasetSource {
    return SqlQueryDatasetSourceToJSONTyped(json, false);
}

export function SqlQueryDatasetSourceToJSONTyped(value?: SqlQueryDatasetSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'sql': value['sql'],
    };
}

