/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';

/**
 * Response returned by APIs that submit a background job (e.g., async refresh).
 * @export
 * @interface SubmitJobResponse
 */
export interface SubmitJobResponse {
    /**
     * Job ID for status polling.
     * @type {string}
     * @memberof SubmitJobResponse
     */
    id: string;
    /**
     * Current status of the submitted job.
     * @type {JobStatus}
     * @memberof SubmitJobResponse
     */
    status: JobStatus;
    /**
     * URL to poll for job status.
     * @type {string}
     * @memberof SubmitJobResponse
     */
    statusUrl: string;
}



/**
 * Check if a given object implements the SubmitJobResponse interface.
 */
export function instanceOfSubmitJobResponse(value: object): value is SubmitJobResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusUrl' in value) || value['statusUrl'] === undefined) return false;
    return true;
}

export function SubmitJobResponseFromJSON(json: any): SubmitJobResponse {
    return SubmitJobResponseFromJSONTyped(json, false);
}

export function SubmitJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': JobStatusFromJSON(json['status']),
        'statusUrl': json['status_url'],
    };
}

export function SubmitJobResponseToJSON(json: any): SubmitJobResponse {
    return SubmitJobResponseToJSONTyped(json, false);
}

export function SubmitJobResponseToJSONTyped(value?: SubmitJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': JobStatusToJSON(value['status']),
        'status_url': value['statusUrl'],
    };
}

