/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColumnInfo } from './ColumnInfo';
import {
    ColumnInfoFromJSON,
    ColumnInfoFromJSONTyped,
    ColumnInfoToJSON,
    ColumnInfoToJSONTyped,
} from './ColumnInfo';

/**
 * Single table metadata
 * @export
 * @interface TableInfo
 */
export interface TableInfo {
    /**
     * 
     * @type {Array<ColumnInfo>}
     * @memberof TableInfo
     */
    columns?: Array<ColumnInfo> | null;
    /**
     * 
     * @type {string}
     * @memberof TableInfo
     */
    connection: string;
    /**
     * 
     * @type {string}
     * @memberof TableInfo
     */
    lastSync?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TableInfo
     */
    schema: string;
    /**
     * 
     * @type {boolean}
     * @memberof TableInfo
     */
    synced: boolean;
    /**
     * 
     * @type {string}
     * @memberof TableInfo
     */
    table: string;
}

/**
 * Check if a given object implements the TableInfo interface.
 */
export function instanceOfTableInfo(value: object): value is TableInfo {
    if (!('connection' in value) || value['connection'] === undefined) return false;
    if (!('schema' in value) || value['schema'] === undefined) return false;
    if (!('synced' in value) || value['synced'] === undefined) return false;
    if (!('table' in value) || value['table'] === undefined) return false;
    return true;
}

export function TableInfoFromJSON(json: any): TableInfo {
    return TableInfoFromJSONTyped(json, false);
}

export function TableInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : ((json['columns'] as Array<any>).map(ColumnInfoFromJSON)),
        'connection': json['connection'],
        'lastSync': json['last_sync'] == null ? undefined : json['last_sync'],
        'schema': json['schema'],
        'synced': json['synced'],
        'table': json['table'],
    };
}

export function TableInfoToJSON(json: any): TableInfo {
    return TableInfoToJSONTyped(json, false);
}

export function TableInfoToJSONTyped(value?: TableInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'] == null ? undefined : ((value['columns'] as Array<any>).map(ColumnInfoToJSON)),
        'connection': value['connection'],
        'last_sync': value['lastSync'],
        'schema': value['schema'],
        'synced': value['synced'],
        'table': value['table'],
    };
}

