/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error details for a failed table refresh
 * @export
 * @interface TableRefreshError
 */
export interface TableRefreshError {
    /**
     * 
     * @type {string}
     * @memberof TableRefreshError
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof TableRefreshError
     */
    schemaName: string;
    /**
     * 
     * @type {string}
     * @memberof TableRefreshError
     */
    tableName: string;
}

/**
 * Check if a given object implements the TableRefreshError interface.
 */
export function instanceOfTableRefreshError(value: object): value is TableRefreshError {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('schemaName' in value) || value['schemaName'] === undefined) return false;
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    return true;
}

export function TableRefreshErrorFromJSON(json: any): TableRefreshError {
    return TableRefreshErrorFromJSONTyped(json, false);
}

export function TableRefreshErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableRefreshError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'schemaName': json['schema_name'],
        'tableName': json['table_name'],
    };
}

export function TableRefreshErrorToJSON(json: any): TableRefreshError {
    return TableRefreshErrorToJSONTyped(json, false);
}

export function TableRefreshErrorToJSONTyped(value?: TableRefreshError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'schema_name': value['schemaName'],
        'table_name': value['tableName'],
    };
}

