/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RefreshWarning } from './RefreshWarning';
import {
    RefreshWarningFromJSON,
    RefreshWarningFromJSONTyped,
    RefreshWarningToJSON,
    RefreshWarningToJSONTyped,
} from './RefreshWarning';

/**
 * Response for single table data refresh
 * @export
 * @interface TableRefreshResult
 */
export interface TableRefreshResult {
    /**
     * 
     * @type {string}
     * @memberof TableRefreshResult
     */
    connectionId: string;
    /**
     * 
     * @type {number}
     * @memberof TableRefreshResult
     */
    durationMs: number;
    /**
     * 
     * @type {number}
     * @memberof TableRefreshResult
     */
    rowsSynced: number;
    /**
     * 
     * @type {string}
     * @memberof TableRefreshResult
     */
    schemaName: string;
    /**
     * 
     * @type {string}
     * @memberof TableRefreshResult
     */
    tableName: string;
    /**
     * 
     * @type {Array<RefreshWarning>}
     * @memberof TableRefreshResult
     */
    warnings?: Array<RefreshWarning>;
}

/**
 * Check if a given object implements the TableRefreshResult interface.
 */
export function instanceOfTableRefreshResult(value: object): value is TableRefreshResult {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('durationMs' in value) || value['durationMs'] === undefined) return false;
    if (!('rowsSynced' in value) || value['rowsSynced'] === undefined) return false;
    if (!('schemaName' in value) || value['schemaName'] === undefined) return false;
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    return true;
}

export function TableRefreshResultFromJSON(json: any): TableRefreshResult {
    return TableRefreshResultFromJSONTyped(json, false);
}

export function TableRefreshResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableRefreshResult {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connection_id'],
        'durationMs': json['duration_ms'],
        'rowsSynced': json['rows_synced'],
        'schemaName': json['schema_name'],
        'tableName': json['table_name'],
        'warnings': json['warnings'] == null ? undefined : ((json['warnings'] as Array<any>).map(RefreshWarningFromJSON)),
    };
}

export function TableRefreshResultToJSON(json: any): TableRefreshResult {
    return TableRefreshResultToJSONTyped(json, false);
}

export function TableRefreshResultToJSONTyped(value?: TableRefreshResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_id': value['connectionId'],
        'duration_ms': value['durationMs'],
        'rows_synced': value['rowsSynced'],
        'schema_name': value['schemaName'],
        'table_name': value['tableName'],
        'warnings': value['warnings'] == null ? undefined : ((value['warnings'] as Array<any>).map(RefreshWarningToJSON)),
    };
}

