/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Date or timestamp column.
 * @export
 * @interface TemporalProfileDetail
 */
export interface TemporalProfileDetail {
    /**
     * Latest value as ISO-8601 string
     * @type {string}
     * @memberof TemporalProfileDetail
     */
    max: string;
    /**
     * Earliest value as ISO-8601 string
     * @type {string}
     * @memberof TemporalProfileDetail
     */
    min: string;
}

/**
 * Check if a given object implements the TemporalProfileDetail interface.
 */
export function instanceOfTemporalProfileDetail(value: object): value is TemporalProfileDetail {
    if (!('max' in value) || value['max'] === undefined) return false;
    if (!('min' in value) || value['min'] === undefined) return false;
    return true;
}

export function TemporalProfileDetailFromJSON(json: any): TemporalProfileDetail {
    return TemporalProfileDetailFromJSONTyped(json, false);
}

export function TemporalProfileDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemporalProfileDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'max': json['max'],
        'min': json['min'],
    };
}

export function TemporalProfileDetailToJSON(json: any): TemporalProfileDetail {
    return TemporalProfileDetailToJSONTyped(json, false);
}

export function TemporalProfileDetailToJSONTyped(value?: TemporalProfileDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max': value['max'],
        'min': value['min'],
    };
}

