/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for PUT /embedding-providers/{id}
 * @export
 * @interface UpdateEmbeddingProviderResponse
 */
export interface UpdateEmbeddingProviderResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateEmbeddingProviderResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmbeddingProviderResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateEmbeddingProviderResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UpdateEmbeddingProviderResponse interface.
 */
export function instanceOfUpdateEmbeddingProviderResponse(value: object): value is UpdateEmbeddingProviderResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UpdateEmbeddingProviderResponseFromJSON(json: any): UpdateEmbeddingProviderResponse {
    return UpdateEmbeddingProviderResponseFromJSONTyped(json, false);
}

export function UpdateEmbeddingProviderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmbeddingProviderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UpdateEmbeddingProviderResponseToJSON(json: any): UpdateEmbeddingProviderResponse {
    return UpdateEmbeddingProviderResponseToJSONTyped(json, false);
}

export function UpdateEmbeddingProviderResponseToJSONTyped(value?: UpdateEmbeddingProviderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

