/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for PUT /embedding-providers/{id}
 * @export
 * @interface UpdateEmbeddingProviderRequest
 */
export interface UpdateEmbeddingProviderRequest {
    /**
     * Inline API key. If provided, updates (or creates) the auto-managed secret.
     * @type {string}
     * @memberof UpdateEmbeddingProviderRequest
     */
    apiKey?: string | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateEmbeddingProviderRequest
     */
    config?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmbeddingProviderRequest
     */
    name?: string | null;
    /**
     * Secret name containing the API key. Pass null to clear.
     * @type {string}
     * @memberof UpdateEmbeddingProviderRequest
     */
    secretName?: string | null;
}

/**
 * Check if a given object implements the UpdateEmbeddingProviderRequest interface.
 */
export function instanceOfUpdateEmbeddingProviderRequest(value: object): value is UpdateEmbeddingProviderRequest {
    return true;
}

export function UpdateEmbeddingProviderRequestFromJSON(json: any): UpdateEmbeddingProviderRequest {
    return UpdateEmbeddingProviderRequestFromJSONTyped(json, false);
}

export function UpdateEmbeddingProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmbeddingProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'config': json['config'] == null ? undefined : json['config'],
        'name': json['name'] == null ? undefined : json['name'],
        'secretName': json['secret_name'] == null ? undefined : json['secret_name'],
    };
}

export function UpdateEmbeddingProviderRequestToJSON(json: any): UpdateEmbeddingProviderRequest {
    return UpdateEmbeddingProviderRequestToJSONTyped(json, false);
}

export function UpdateEmbeddingProviderRequestToJSONTyped(value?: UpdateEmbeddingProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
        'config': value['config'],
        'name': value['name'],
        'secret_name': value['secretName'],
    };
}

