/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for PUT /v1/queries/{id}
 * @export
 * @interface UpdateSavedQueryRequest
 */
export interface UpdateSavedQueryRequest {
    /**
     * Override the auto-detected category. Send `null` to clear (revert to auto).
     * @type {string}
     * @memberof UpdateSavedQueryRequest
     */
    categoryOverride?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedQueryRequest
     */
    description?: string | null;
    /**
     * Optional new name. When omitted the existing name is preserved.
     * @type {string}
     * @memberof UpdateSavedQueryRequest
     */
    name?: string | null;
    /**
     * Optional new SQL. When omitted the existing SQL is preserved.
     * @type {string}
     * @memberof UpdateSavedQueryRequest
     */
    sql?: string | null;
    /**
     * User annotation for table size. Send `null` to clear.
     * @type {string}
     * @memberof UpdateSavedQueryRequest
     */
    tableSizeOverride?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateSavedQueryRequest
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the UpdateSavedQueryRequest interface.
 */
export function instanceOfUpdateSavedQueryRequest(value: object): value is UpdateSavedQueryRequest {
    return true;
}

export function UpdateSavedQueryRequestFromJSON(json: any): UpdateSavedQueryRequest {
    return UpdateSavedQueryRequestFromJSONTyped(json, false);
}

export function UpdateSavedQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSavedQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryOverride': json['category_override'] == null ? undefined : json['category_override'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'sql': json['sql'] == null ? undefined : json['sql'],
        'tableSizeOverride': json['table_size_override'] == null ? undefined : json['table_size_override'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function UpdateSavedQueryRequestToJSON(json: any): UpdateSavedQueryRequest {
    return UpdateSavedQueryRequestToJSONTyped(json, false);
}

export function UpdateSavedQueryRequestToJSONTyped(value?: UpdateSavedQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category_override': value['categoryOverride'],
        'description': value['description'],
        'name': value['name'],
        'sql': value['sql'],
        'table_size_override': value['tableSizeOverride'],
        'tags': value['tags'],
    };
}

