/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Partial update — only the provided fields are changed.
 * @export
 * @interface UpdateSandboxRequest
 */
export interface UpdateSandboxRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSandboxRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSandboxRequest
     */
    markdown?: string;
}

/**
 * Check if a given object implements the UpdateSandboxRequest interface.
 */
export function instanceOfUpdateSandboxRequest(value: object): value is UpdateSandboxRequest {
    return true;
}

export function UpdateSandboxRequestFromJSON(json: any): UpdateSandboxRequest {
    return UpdateSandboxRequestFromJSONTyped(json, false);
}

export function UpdateSandboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSandboxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'markdown': json['markdown'] == null ? undefined : json['markdown'],
    };
}

export function UpdateSandboxRequestToJSON(json: any): UpdateSandboxRequest {
    return UpdateSandboxRequestToJSONTyped(json, false);
}

export function UpdateSandboxRequestToJSONTyped(value?: UpdateSandboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'markdown': value['markdown'],
    };
}

