/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for PUT /secrets/{name}
 * @export
 * @interface UpdateSecretRequest
 */
export interface UpdateSecretRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSecretRequest
     */
    value: string;
}

/**
 * Check if a given object implements the UpdateSecretRequest interface.
 */
export function instanceOfUpdateSecretRequest(value: object): value is UpdateSecretRequest {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function UpdateSecretRequestFromJSON(json: any): UpdateSecretRequest {
    return UpdateSecretRequestFromJSONTyped(json, false);
}

export function UpdateSecretRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSecretRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function UpdateSecretRequestToJSON(json: any): UpdateSecretRequest {
    return UpdateSecretRequestToJSONTyped(json, false);
}

export function UpdateSecretRequestToJSONTyped(value?: UpdateSecretRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

