/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for PUT /secrets/{name}
 * @export
 * @interface UpdateSecretResponse
 */
export interface UpdateSecretResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateSecretResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSecretResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UpdateSecretResponse interface.
 */
export function instanceOfUpdateSecretResponse(value: object): value is UpdateSecretResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UpdateSecretResponseFromJSON(json: any): UpdateSecretResponse {
    return UpdateSecretResponseFromJSONTyped(json, false);
}

export function UpdateSecretResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSecretResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UpdateSecretResponseToJSON(json: any): UpdateSecretResponse {
    return UpdateSecretResponseToJSONTyped(json, false);
}

export function UpdateSecretResponseToJSONTyped(value?: UpdateSecretResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

