/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for PUT /v1/datasets/{id}
 * @export
 * @interface UpdateDatasetResponse
 */
export interface UpdateDatasetResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateDatasetResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDatasetResponse
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDatasetResponse
     */
    tableName: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateDatasetResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UpdateDatasetResponse interface.
 */
export function instanceOfUpdateDatasetResponse(value: object): value is UpdateDatasetResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UpdateDatasetResponseFromJSON(json: any): UpdateDatasetResponse {
    return UpdateDatasetResponseFromJSONTyped(json, false);
}

export function UpdateDatasetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDatasetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'tableName': json['table_name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UpdateDatasetResponseToJSON(json: any): UpdateDatasetResponse {
    return UpdateDatasetResponseToJSONTyped(json, false);
}

export function UpdateDatasetResponseToJSONTyped(value?: UpdateDatasetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'table_name': value['tableName'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

