/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for PUT /v1/datasets/{id}
 * @export
 * @interface UpdateDatasetRequest
 */
export interface UpdateDatasetRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateDatasetRequest
     */
    label?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateDatasetRequest
     */
    tableName?: string | null;
}

/**
 * Check if a given object implements the UpdateDatasetRequest interface.
 */
export function instanceOfUpdateDatasetRequest(value: object): value is UpdateDatasetRequest {
    return true;
}

export function UpdateDatasetRequestFromJSON(json: any): UpdateDatasetRequest {
    return UpdateDatasetRequestFromJSONTyped(json, false);
}

export function UpdateDatasetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDatasetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'tableName': json['table_name'] == null ? undefined : json['table_name'],
    };
}

export function UpdateDatasetRequestToJSON(json: any): UpdateDatasetRequest {
    return UpdateDatasetRequestToJSONTyped(json, false);
}

export function UpdateDatasetRequestToJSONTyped(value?: UpdateDatasetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'table_name': value['tableName'],
    };
}

