/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create dataset from a previously uploaded file
 * @export
 * @interface UploadDatasetSource
 */
export interface UploadDatasetSource {
    /**
     * Optional explicit column definitions. Keys are column names, values are type specs.
     * When provided, the schema is built from these definitions instead of being inferred.
     * @type {{ [key: string]: string; }}
     * @memberof UploadDatasetSource
     */
    columns?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof UploadDatasetSource
     */
    format?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UploadDatasetSource
     */
    uploadId: string;
}

/**
 * Check if a given object implements the UploadDatasetSource interface.
 */
export function instanceOfUploadDatasetSource(value: object): value is UploadDatasetSource {
    if (!('uploadId' in value) || value['uploadId'] === undefined) return false;
    return true;
}

export function UploadDatasetSourceFromJSON(json: any): UploadDatasetSource {
    return UploadDatasetSourceFromJSONTyped(json, false);
}

export function UploadDatasetSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadDatasetSource {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : json['columns'],
        'format': json['format'] == null ? undefined : json['format'],
        'uploadId': json['upload_id'],
    };
}

export function UploadDatasetSourceToJSON(json: any): UploadDatasetSource {
    return UploadDatasetSourceToJSONTyped(json, false);
}

export function UploadDatasetSourceToJSONTyped(value?: UploadDatasetSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'],
        'format': value['format'],
        'upload_id': value['uploadId'],
    };
}

