/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single upload info for listing
 * @export
 * @interface UploadInfo
 */
export interface UploadInfo {
    /**
     * 
     * @type {string}
     * @memberof UploadInfo
     */
    contentType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UploadInfo
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UploadInfo
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof UploadInfo
     */
    sizeBytes: number;
    /**
     * 
     * @type {string}
     * @memberof UploadInfo
     */
    status: string;
}

/**
 * Check if a given object implements the UploadInfo interface.
 */
export function instanceOfUploadInfo(value: object): value is UploadInfo {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UploadInfoFromJSON(json: any): UploadInfo {
    return UploadInfoFromJSONTyped(json, false);
}

export function UploadInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'sizeBytes': json['size_bytes'],
        'status': json['status'],
    };
}

export function UploadInfoToJSON(json: any): UploadInfo {
    return UploadInfoToJSONTyped(json, false);
}

export function UploadInfoToJSONTyped(value?: UploadInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': value['contentType'],
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'size_bytes': value['sizeBytes'],
        'status': value['status'],
    };
}

