/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /v1/files
 * @export
 * @interface UploadResponse
 */
export interface UploadResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    contentType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UploadResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof UploadResponse
     */
    sizeBytes: number;
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    status: string;
}

/**
 * Check if a given object implements the UploadResponse interface.
 */
export function instanceOfUploadResponse(value: object): value is UploadResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UploadResponseFromJSON(json: any): UploadResponse {
    return UploadResponseFromJSONTyped(json, false);
}

export function UploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'sizeBytes': json['size_bytes'],
        'status': json['status'],
    };
}

export function UploadResponseToJSON(json: any): UploadResponse {
    return UploadResponseToJSONTyped(json, false);
}

export function UploadResponseToJSONTyped(value?: UploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': value['contentType'],
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'size_bytes': value['sizeBytes'],
        'status': value['status'],
    };
}

