/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceContextEntry } from './WorkspaceContextEntry';
import {
    WorkspaceContextEntryFromJSON,
    WorkspaceContextEntryFromJSONTyped,
    WorkspaceContextEntryToJSON,
    WorkspaceContextEntryToJSONTyped,
} from './WorkspaceContextEntry';

/**
 * Response body for POST `/v1/context`.
 * @export
 * @interface UpsertWorkspaceContextResponse
 */
export interface UpsertWorkspaceContextResponse {
    /**
     * 
     * @type {WorkspaceContextEntry}
     * @memberof UpsertWorkspaceContextResponse
     */
    context: WorkspaceContextEntry;
}

/**
 * Check if a given object implements the UpsertWorkspaceContextResponse interface.
 */
export function instanceOfUpsertWorkspaceContextResponse(value: object): value is UpsertWorkspaceContextResponse {
    if (!('context' in value) || value['context'] === undefined) return false;
    return true;
}

export function UpsertWorkspaceContextResponseFromJSON(json: any): UpsertWorkspaceContextResponse {
    return UpsertWorkspaceContextResponseFromJSONTyped(json, false);
}

export function UpsertWorkspaceContextResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertWorkspaceContextResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'context': WorkspaceContextEntryFromJSON(json['context']),
    };
}

export function UpsertWorkspaceContextResponseToJSON(json: any): UpsertWorkspaceContextResponse {
    return UpsertWorkspaceContextResponseToJSONTyped(json, false);
}

export function UpsertWorkspaceContextResponseToJSONTyped(value?: UpsertWorkspaceContextResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': WorkspaceContextEntryToJSON(value['context']),
    };
}

