/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST `/v1/context`.
 * @export
 * @interface UpsertWorkspaceContextRequest
 */
export interface UpsertWorkspaceContextRequest {
    /**
     * 
     * @type {string}
     * @memberof UpsertWorkspaceContextRequest
     */
    content: string;
    /**
     * Unique name in the catalog (upsert key). Same field as in list/get responses.
     * @type {string}
     * @memberof UpsertWorkspaceContextRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpsertWorkspaceContextRequest interface.
 */
export function instanceOfUpsertWorkspaceContextRequest(value: object): value is UpsertWorkspaceContextRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpsertWorkspaceContextRequestFromJSON(json: any): UpsertWorkspaceContextRequest {
    return UpsertWorkspaceContextRequestFromJSONTyped(json, false);
}

export function UpsertWorkspaceContextRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertWorkspaceContextRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'name': json['name'],
    };
}

export function UpsertWorkspaceContextRequestToJSON(json: any): UpsertWorkspaceContextRequest {
    return UpsertWorkspaceContextRequestToJSONTyped(json, false);
}

export function UpsertWorkspaceContextRequestToJSONTyped(value?: UpsertWorkspaceContextRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'name': value['name'],
    };
}

