/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create dataset from an external HTTP URL
 * @export
 * @interface UrlDatasetSource
 */
export interface UrlDatasetSource {
    /**
     * Optional explicit column definitions. Keys are column names, values are type specs.
     * @type {{ [key: string]: string; }}
     * @memberof UrlDatasetSource
     */
    columns?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof UrlDatasetSource
     */
    format?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UrlDatasetSource
     */
    url: string;
}

/**
 * Check if a given object implements the UrlDatasetSource interface.
 */
export function instanceOfUrlDatasetSource(value: object): value is UrlDatasetSource {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function UrlDatasetSourceFromJSON(json: any): UrlDatasetSource {
    return UrlDatasetSourceFromJSONTyped(json, false);
}

export function UrlDatasetSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlDatasetSource {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : json['columns'],
        'format': json['format'] == null ? undefined : json['format'],
        'url': json['url'],
    };
}

export function UrlDatasetSourceToJSON(json: any): UrlDatasetSource {
    return UrlDatasetSourceToJSONTyped(json, false);
}

export function UrlDatasetSourceToJSONTyped(value?: UrlDatasetSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'],
        'format': value['format'],
        'url': value['url'],
    };
}

