/* tslint:disable */
/* eslint-disable */
/**
 * Hotdata API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@hotdata.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One context entry returned by the API.
 * @export
 * @interface WorkspaceContextEntry
 */
export interface WorkspaceContextEntry {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceContextEntry
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceContextEntry
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkspaceContextEntry
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the WorkspaceContextEntry interface.
 */
export function instanceOfWorkspaceContextEntry(value: object): value is WorkspaceContextEntry {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WorkspaceContextEntryFromJSON(json: any): WorkspaceContextEntry {
    return WorkspaceContextEntryFromJSONTyped(json, false);
}

export function WorkspaceContextEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceContextEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function WorkspaceContextEntryToJSON(json: any): WorkspaceContextEntry {
    return WorkspaceContextEntryToJSONTyped(json, false);
}

export function WorkspaceContextEntryToJSONTyped(value?: WorkspaceContextEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'name': value['name'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

