/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceDetail
 */
export interface WorkspaceDetail {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceDetail
     */
    publicId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceDetail
     */
    provisionStatus: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceDetail
     */
    namespace: string;
}

/**
 * Check if a given object implements the WorkspaceDetail interface.
 */
export function instanceOfWorkspaceDetail(value: object): value is WorkspaceDetail {
    if (!('publicId' in value) || value['publicId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provisionStatus' in value) || value['provisionStatus'] === undefined) return false;
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    return true;
}

export function WorkspaceDetailFromJSON(json: any): WorkspaceDetail {
    return WorkspaceDetailFromJSONTyped(json, false);
}

export function WorkspaceDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'publicId': json['public_id'],
        'name': json['name'],
        'provisionStatus': json['provision_status'],
        'namespace': json['namespace'],
    };
}

export function WorkspaceDetailToJSON(json: any): WorkspaceDetail {
    return WorkspaceDetailToJSONTyped(json, false);
}

export function WorkspaceDetailToJSONTyped(value?: WorkspaceDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_id': value['publicId'],
        'name': value['name'],
        'provision_status': value['provisionStatus'],
        'namespace': value['namespace'],
    };
}

