/* tslint:disable */
/* eslint-disable */
/**
 * HotData API
 * Powerful data platform API for datasets, queries, and analytics.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceListItem
 */
export interface WorkspaceListItem {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceListItem
     */
    publicId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceListItem
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceListItem
     */
    active: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceListItem
     */
    favorite: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceListItem
     */
    provisionStatus: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceListItem
     */
    namespace: string;
}

/**
 * Check if a given object implements the WorkspaceListItem interface.
 */
export function instanceOfWorkspaceListItem(value: object): value is WorkspaceListItem {
    if (!('publicId' in value) || value['publicId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('favorite' in value) || value['favorite'] === undefined) return false;
    if (!('provisionStatus' in value) || value['provisionStatus'] === undefined) return false;
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    return true;
}

export function WorkspaceListItemFromJSON(json: any): WorkspaceListItem {
    return WorkspaceListItemFromJSONTyped(json, false);
}

export function WorkspaceListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'publicId': json['public_id'],
        'name': json['name'],
        'active': json['active'],
        'favorite': json['favorite'],
        'provisionStatus': json['provision_status'],
        'namespace': json['namespace'],
    };
}

export function WorkspaceListItemToJSON(json: any): WorkspaceListItem {
    return WorkspaceListItemToJSONTyped(json, false);
}

export function WorkspaceListItemToJSONTyped(value?: WorkspaceListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_id': value['publicId'],
        'name': value['name'],
        'active': value['active'],
        'favorite': value['favorite'],
        'provision_status': value['provisionStatus'],
        'namespace': value['namespace'],
    };
}

